FROM mcr.microsoft.com/dotnet/runtime:10.0-windowsservercore-ltsc2025

ARG M365DSC_VERSION
ENV M365DSC_VERSION=${M365DSC_VERSION:-latest}

WORKDIR /DSC

COPY ./Modules/Microsoft365DSC/Microsoft365DSC.psd1 /DSC/Microsoft365DSC.psd1
COPY ./Utilities/Install-M365DSCAndDependencies.ps1 /DSC/Install-M365DSCAndDependencies.ps1

SHELL ["cmd", "/S", "/C"]

RUN powershell -Command '$null = Install-Module -Name "Microsoft.PowerShell.PSResourceGet" -Repository "PSGallery" -Scope "AllUsers" -Force -SkipPublisherCheck'
RUN powershell -Command '$null = Install-PSResource -Name "Pester" -Repository "PSGallery" -Scope "AllUsers" -SkipDependencyCheck -TrustRepository -AcceptLicense'
RUN powershell -Command '$null = Install-PSResource -Name "M365DSC.PSDesiredStateConfiguration" -Repository "PSGallery" -Scope "AllUsers" -SkipDependencyCheck -TrustRepository -AcceptLicense'

RUN powershell -Command .\Install-M365DSCAndDependencies.ps1 -M365DSCVersion %M365DSC_VERSION%

ENTRYPOINT ["pwsh", "-NoLogo"]
