FROM mcr.microsoft.com/dotnet/runtime:10.0-resolute

WORKDIR /DSC

SHELL ["bash", "-c"]

COPY ./Utilities/Install-M365DSCAndDependencies.ps1 /DSC/Install-M365DSCAndDependencies.ps1

RUN apt-get update && apt-get install -y \
    wget \
    curl \
    libgssapi-krb5-2 \
    && rm -rf /var/lib/apt/lists/*

RUN wget -q https://packages.microsoft.com/ubuntu/24.04/prod/pool/main/p/powershell/powershell_7.6.6-1.deb_amd64.deb && \
    dpkg -i powershell_7.6.6-1.deb_amd64.deb && \
    rm powershell_7.6.6-1.deb_amd64.deb

RUN wget -q https://github.com/microsoft/omi/releases/download/v1.9.1-0/omi-1.9.1-0.ssl_300.ulinux.s.x64.deb && \
    dpkg -i ./omi-1.9.1-0.ssl_300.ulinux.s.x64.deb && \
    rm ./omi-1.9.1-0.ssl_300.ulinux.s.x64.deb && \
    cp /opt/omi/lib/libmi.so /opt/microsoft/powershell/7/

RUN wget -q https://github.com/microsoft/PowerShell-DSC-for-Linux/releases/download/v1.2.4-0/dsc-1.2.4-0.ssl_110.x64.deb && \
    dpkg -i ./dsc-1.2.4-0.ssl_110.x64.deb && \
    rm ./dsc-1.2.4-0.ssl_110.x64.deb

RUN wget https://archive.ubuntu.com/ubuntu/pool/main/n/nano/nano_9.2-1_amd64.deb && \
    dpkg -i ./nano_9.2-1_amd64.deb && \
    rm nano_9.2-1_amd64.deb

RUN mv /etc/opt/omi/conf/dsc/configuration/baseregistration /etc/opt/omi/conf/dsc/configuration/BaseRegistration && \
    mv /etc/opt/omi/conf/dsc/configuration/BaseRegistration/baseresource.schema.mof /etc/opt/omi/conf/dsc/configuration/BaseRegistration/BaseResource.schema.mof

RUN pwsh -Command 'Install-Module -Name "Microsoft.PowerShell.PSResourceGet" -Repository "PSGallery" -Scope "AllUsers" -Force -SkipPublisherCheck'
RUN pwsh -Command 'Save-PSResource -Name "Microsoft365Dsc" -Repository "PSGallery" -Path "/usr/local/share/powershell/Modules" -SkipDependencyCheck -TrustRepository -AcceptLicense'
RUN pwsh -Command 'Install-PSResource -Name "Pester" -Repository "PSGallery" -Scope "AllUsers" -SkipDependencyCheck -TrustRepository -AcceptLicense'
RUN pwsh -Command 'Install-PSResource -Name "M365DSC.PSDesiredStateConfiguration" -Repository "PSGallery" -Scope "AllUsers" -SkipDependencyCheck -TrustRepository -AcceptLicense'

RUN pwsh -Command ./Install-M365DSCAndDependencies.ps1

ENTRYPOINT ["pwsh", "-NoLogo"]
