/*
@TargetNode='localhost'
@GeneratedBy=Daniel.King
@GenerationDate=11/26/2024 11:36:33
@GenerationHost=APS-LP-01
*/

instance of MSFT_IntuneTrustedRootCertificateIOS as $MSFT_IntuneTrustedRootCertificateIOS1ref
{
ResourceID = "[IntuneTrustedRootCertificateIOS]ConfigureIntuneTrustedRootCertificateIOS";
 TenantId = "dannykbjj.onmicrosoft.com";
 SourceInfo = "C:\\DannyKBjj-m365\\Scripts\\M365cERTS\\Examples\\IntuneTrustedRootCertificateIOS\\3-Remove.ps1::24::9::IntuneTrustedRootCertificateIOS";
 Description = "IntuneTrustedRootCertificateIOS Description";
 DisplayName = "IntuneTrustedRootCertificateIOS DisplayName";
 CertificateThumbprint = "9F0693132A67CAE57294E51E78C433CD06453385";
 Ensure = "Absent";
 ModuleVersion = "1.24.1120.1";
 ModuleName = "Microsoft365DSC";
 ApplicationId = "0560895e-2743-4ba1-a92a-45c8088a7f6d";
 ConfigurationName = "Example";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="Daniel.King";

                        GenerationDate="11/26/2024 11:36:33";

                        GenerationHost="APS-LP-01";

                        Name="Example";

                    };
