# Editor-only: lets this file resolve [M365DSCResourceBase] when parsed on its own.
# Build-Microsoft365DSC.ps1 emits only the class extent, so this line is not shipped.
using module ..\_Base\M365DSCResourceBase.psm1

[DscResource()]
class IntuneWindowsAutopilotDeploymentProfileAzureADJoined : M365DSCResourceBase
{
    [DscProperty()]
    [System.ComponentModel.Description('Description of the profile')]
    [System.String] $Description

    [DscProperty()]
    [System.ComponentModel.Description('The template used to name the AutoPilot Device. This can be a custom text and can also contain either the serial number of the device, or a randomly generated number. The total length of the text generated by the template can be no more than 15 characters.')]
    [System.String] $DeviceNameTemplate

    [DscProperty()]
    [System.ComponentModel.Description('The AutoPilot device type that this profile is applicable to. Possible values are: windowsPc, surfaceHub2.')]
    [ValidateSet('windowsPc', 'surfaceHub2', 'holoLens', 'surfaceHub2S', 'virtualMachine', 'unknownFutureValue')]
    [System.String] $DeviceType

    [DscProperty(Key)]
    [System.ComponentModel.Description('Name of the profile')]
    [System.String] $DisplayName

    [DscProperty()]
    [System.ComponentModel.Description('Whether the profile allows pre-provisioned deployment.')]
    [System.Nullable[System.Boolean]] $PreprovisioningAllowed

    [DscProperty()]
    [System.ComponentModel.Description('Enrollment status screen setting')]
    [MSFT_MicrosoftGraphwindowsEnrollmentStatusScreenSettings1] $EnrollmentStatusScreenSettings

    [DscProperty()]
    [System.ComponentModel.Description('Whether the profile extracts the hardware hash of the device.')]
    [System.Nullable[System.Boolean]] $HardwareHashExtractionEnabled

    [DscProperty()]
    [System.ComponentModel.Description('Locale configured on the device')]
    [System.String] $Locale

    [DscProperty()]
    [System.ComponentModel.Description('AzureAD management app ID used during client device-based enrollment discovery')]
    [System.String] $ManagementServiceAppId

    [DscProperty()]
    [System.ComponentModel.Description('The Windows Autopilot Deployment Profile settings used by the device for the out of box experience.')]
    [MSFT_MicrosoftGraphoutOfBoxExperienceSetting] $OutOfBoxExperienceSetting

    [DscProperty()]
    [System.ComponentModel.Description('The unique identifier for an entity. Read-only.')]
    [System.String] $Id

    [DscProperty()]
    [System.ComponentModel.Description('List of Scope Tags for this Entity instance.')]
    [System.String[]] $RoleScopeTagIds

    [DscProperty()]
    [System.ComponentModel.Description('Represents the assignment to the Intune policy.')]
    [MSFT_DeviceManagementConfigurationPolicyAssignments[]] $Assignments

    [DscProperty()]
    [System.ComponentModel.Description('Present ensures the policy exists, absent ensures it is removed.')]
    [ValidateSet('Present', 'Absent')]
    [System.String] $Ensure

    [DscProperty()]
    [System.ComponentModel.Description('Credentials of the Admin')]
    [System.Management.Automation.PSCredential] $Credential

    [DscProperty()]
    [System.ComponentModel.Description('Id of the Azure Active Directory application to authenticate with.')]
    [System.String] $ApplicationId

    [DscProperty()]
    [System.ComponentModel.Description('Id of the Azure Active Directory tenant used for authentication.')]
    [System.String] $TenantId

    [DscProperty()]
    [System.ComponentModel.Description('Secret of the Azure Active Directory tenant used for authentication.')]
    [System.Management.Automation.PSCredential] $ApplicationSecret

    [DscProperty()]
    [System.ComponentModel.Description('Thumbprint of the Azure Active Directory application''s authentication certificate to use for authentication.')]
    [System.String] $CertificateThumbprint

    [DscProperty()]
    [System.ComponentModel.Description('Username can be made up to anything but password will be used for CertificatePassword')]
    [System.Management.Automation.PSCredential] $CertificatePassword

    [DscProperty()]
    [System.ComponentModel.Description('Path to certificate used in service principal usually a PFX file.')]
    [System.String] $CertificatePath

    [DscProperty()]
    [System.ComponentModel.Description('Managed ID being used for authentication.')]
    [System.Nullable[System.Boolean]] $ManagedIdentity

    [DscProperty()]
    [System.ComponentModel.Description('Access token used for authentication.')]
    [System.String[]] $AccessTokens

    # Export-only. Not part of the resource schema.
    [System.String] $Filter

    [IntuneWindowsAutopilotDeploymentProfileAzureADJoined] Get()
    {
        if ($this.RequiresPowerShellCore())
        {
            $remote = [IntuneWindowsAutopilotDeploymentProfileAzureADJoined]::new()
            $remote.FromHashtable($this.InvokeInPowerShellCore('Get'))
            return $remote
        }

        Write-Verbose -Message "Getting configuration of the Intune Windows Autopilot Deployment Profile Azure AD Joined with Id {$($this.Id)} and DisplayName {$($this.DisplayName)}"

        try
        {
            if (-not $this.ExportedInstance -or $this.ExportedInstance.DisplayName -ne $this.DisplayName)
            {
                $null = $this.Connect('MicrosoftGraph')

                #Ensure the proper dependencies are installed in the current environment.
                Confirm-M365DSCDependencies

                #region Telemetry
                $this.AddTelemetry('Get')
                #endregion

                $nullResult = $this.GetBoundParameters()
                $nullResult.Ensure = 'Absent'

                $getValue = $null
                #region resource generator code
                if (-not [string]::IsNullOrEmpty($this.Id))
                {
                    $getValue = Get-MgBetaDeviceManagementWindowsAutopilotDeploymentProfile -WindowsAutopilotDeploymentProfileId $this.Id -ErrorAction SilentlyContinue `
                        | Where-Object -FilterScript { $null -ne $_.DisplayName }
                }

                if ($null -eq $getValue)
                {
                    Write-Verbose -Message "Could not find an Intune Windows Autopilot Deployment Profile Azure AD Joined with Id {$($this.Id)}"

                    if (-not [string]::IsNullOrEmpty($this.DisplayName))
                    {
                        $getValue = Get-MgBetaDeviceManagementWindowsAutopilotDeploymentProfile `
                            -All `
                            -Filter "DisplayName eq '$($this.DisplayName -replace "'", "''")'" `
                            -ErrorAction SilentlyContinue `
                        | Where-Object -FilterScript { $null -ne $_.DisplayName }
                    }
                }
                #endregion
                if ($null -eq $getValue)
                {
                    Write-Verbose -Message "Could not find an Intune Windows Autopilot Deployment Profile Azure AD Joined with DisplayName {$($this.DisplayName)}"
                    return $this.AsResult($nullResult)
                }

                if ($getValue -is [array])
                {
                    throw "The DisplayName {$($this.DisplayName)} returned multiple policies, make sure DisplayName is unique."
                }
            }
            else
            {
                $getValue = $this.ExportedInstance
            }

            $resolvedId = $getValue.Id
            Write-Verbose -Message "An Intune Windows Autopilot Deployment Profile Azure AD Joined with Id {$($resolvedId)} and DisplayName {$($this.DisplayName)} was found."

            #region resource generator code
            $complexEnrollmentStatusScreenSettings = [ordered]@{}
            $complexEnrollmentStatusScreenSettings.Add('AllowDeviceUseBeforeProfileAndAppInstallComplete', $getValue.EnrollmentStatusScreenSettings.allowDeviceUseBeforeProfileAndAppInstallComplete)
            $complexEnrollmentStatusScreenSettings.Add('AllowDeviceUseOnInstallFailure', $getValue.EnrollmentStatusScreenSettings.allowDeviceUseOnInstallFailure)
            $complexEnrollmentStatusScreenSettings.Add('AllowLogCollectionOnInstallFailure', $getValue.EnrollmentStatusScreenSettings.allowLogCollectionOnInstallFailure)
            $complexEnrollmentStatusScreenSettings.Add('BlockDeviceSetupRetryByUser', $getValue.EnrollmentStatusScreenSettings.blockDeviceSetupRetryByUser)
            $complexEnrollmentStatusScreenSettings.Add('CustomErrorMessage', $getValue.EnrollmentStatusScreenSettings.customErrorMessage)
            $complexEnrollmentStatusScreenSettings.Add('HideInstallationProgress', $getValue.EnrollmentStatusScreenSettings.hideInstallationProgress)
            $complexEnrollmentStatusScreenSettings.Add('InstallProgressTimeoutInMinutes', $getValue.EnrollmentStatusScreenSettings.installProgressTimeoutInMinutes)
            if ($complexEnrollmentStatusScreenSettings.values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexEnrollmentStatusScreenSettings = $null
            }

            $complexOutOfBoxExperienceSetting = [ordered]@{}
            if ($null -ne $getValue.OutOfBoxExperienceSetting.deviceUsageType)
            {
                $complexOutOfBoxExperienceSetting.Add('DeviceUsageType', $getValue.OutOfBoxExperienceSetting.deviceUsageType.ToString())
            }
            $complexOutOfBoxExperienceSetting.Add('EscapeLinkHidden', $getValue.OutOfBoxExperienceSetting.escapeLinkHidden)
            $complexOutOfBoxExperienceSetting.Add('EulaHidden', $getValue.OutOfBoxExperienceSetting.eulaHidden)
            $complexOutOfBoxExperienceSetting.Add('KeyboardSelectionPageSkipped', $getValue.OutOfBoxExperienceSetting.keyboardSelectionPageSkipped)
            $complexOutOfBoxExperienceSetting.Add('PrivacySettingsHidden', $getValue.OutOfBoxExperienceSetting.privacySettingsHidden)
            if ($null -ne $getValue.OutOfBoxExperienceSetting.userType)
            {
                $complexOutOfBoxExperienceSetting.Add('UserType', $getValue.OutOfBoxExperienceSetting.userType.ToString())
            }
            if ($complexOutOfBoxExperienceSetting.values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexOutOfBoxExperienceSetting = $null
            }
            #endregion

            #region resource generator code
            $enumDeviceType = $null
            if ($null -ne $getValue.DeviceType)
            {
                $enumDeviceType = $getValue.DeviceType.ToString()
            }
            #endregion

            $results = @{
                #region resource generator code
                Description                    = $getValue.Description
                DeviceNameTemplate             = $getValue.DeviceNameTemplate
                DeviceType                     = $enumDeviceType
                DisplayName                    = $getValue.DisplayName
                PreprovisioningAllowed         = $getValue.PreprovisioningAllowed
                EnrollmentStatusScreenSettings = $complexEnrollmentStatusScreenSettings
                HardwareHashExtractionEnabled  = $getValue.HardwareHashExtractionEnabled
                Locale                         = $getValue.Locale
                ManagementServiceAppId         = $getValue.ManagementServiceAppId
                OutOfBoxExperienceSetting      = $complexOutOfBoxExperienceSetting
                Id                             = $getValue.Id
                RoleScopeTagIds                = $getValue.RoleScopeTagIds
                Ensure                         = 'Present'
                Credential                     = $this.Credential
                ApplicationId                  = $this.ApplicationId
                TenantId                       = $this.TenantId
                ApplicationSecret              = $this.ApplicationSecret
                CertificateThumbprint          = $this.CertificateThumbprint
                CertificatePath                = $this.CertificatePath
                CertificatePassword            = $this.CertificatePassword
                ManagedIdentity                = $this.ManagedIdentity.IsPresent
                AccessTokens                   = $this.AccessTokens
                #endregion
            }

            $rawAssignments = @()
            $rawAssignments = Get-MgBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment -WindowsAutopilotDeploymentProfileId $resolvedId -All
            $assignmentResult = @()
            if ($null -ne $rawAssignments -and $rawAssignments.Count -gt 0)
            {
                [array]$rawAssignments = $rawAssignments | Where-Object -FilterScript { $_.source -eq 'direct' }
                $assignmentResult += ConvertFrom-IntunePolicyAssignment -Assignments $rawAssignments -IncludeDeviceFilter $false
            }
            $results.Add('Assignments', $assignmentResult)

            return $this.AsResult($results)
        }
        catch
        {
            $this.LogError($_, 'Error retrieving data:')

            throw
        }
    }

    [void] Set()
    {
        if ($this.RequiresPowerShellCore())
        {
            $null = $this.InvokeInPowerShellCore('Set')
            return
        }

        #Ensure the proper dependencies are installed in the current environment.
        Confirm-M365DSCDependencies

        #region Telemetry
        $this.AddTelemetry('Set')
        #endregion

        $currentInstance = $this.Get().ToHashtable()
        $boundParameters = Remove-M365DSCAuthenticationParameter -BoundParameters $this.GetBoundParameters()

        if ($this.Ensure -eq 'Present' -and $currentInstance.Ensure -eq 'Absent')
        {
            Write-Verbose -Message "Creating an Intune Windows Autopilot Deployment Profile Azure AD Joined with DisplayName {$($this.DisplayName)}"
            $createParameters = ([Hashtable]$boundParameters).Clone()
            $createParameters = Rename-M365DSCCimInstanceParameter -Properties $createParameters
            $createParameters.Remove('Assignments') | Out-Null
            $createParameters.Remove('Id') | Out-Null

            #region resource generator code
            $CreateParameters.Add('@odata.type', '#microsoft.graph.azureADWindowsAutopilotDeploymentProfile')
            $policy = New-MgBetaDeviceManagementWindowsAutopilotDeploymentProfile -BodyParameter $CreateParameters
            #endregion

            #region new Intune assignment management
            $intuneAssignments = @()
            if ($null -ne $this.Assignments -and $this.Assignments.Count -gt 0)
            {
                $intuneAssignments += ConvertTo-IntunePolicyAssignment -Assignments $this.Assignments
            }
            foreach ($assignment in $intuneAssignments)
            {
                New-MgBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment `
                    -WindowsAutopilotDeploymentProfileId $policy.id `
                    -BodyParameter $assignment
            }
            #endregion
        }
        elseif ($this.Ensure -eq 'Present' -and $currentInstance.Ensure -eq 'Present')
        {
            Write-Verbose -Message "Updating the Intune Windows Autopilot Deployment Profile Azure AD Joined with Id {$($currentInstance.Id)}"
            $UpdateParameters = ([Hashtable]$boundParameters).Clone()
            $UpdateParameters = Rename-M365DSCCimInstanceParameter -Properties $UpdateParameters
            $UpdateParameters.Remove('Assignments') | Out-Null
            $UpdateParameters.Remove('Id') | Out-Null
            $UpdateParameters.Remove('DeviceType') | Out-Null

            #region resource generator code
            $UpdateParameters.Add('@odata.type', '#microsoft.graph.azureADWindowsAutopilotDeploymentProfile')
            Update-MgBetaDeviceManagementWindowsAutopilotDeploymentProfile `
                -WindowsAutopilotDeploymentProfileId $currentInstance.Id `
                -BodyParameter $UpdateParameters
            #endregion

            #region new Intune assignment management
            $currentAssignments = @()
            $currentAssignments += Get-MgBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment -WindowsAutopilotDeploymentProfileId $currentInstance.id
            $currentAssignments = $currentAssignments | Where-Object -FilterScript { $_.source -eq 'direct' }

            $intuneAssignments = @()
            if ($null -ne $this.Assignments -and $this.Assignments.Count -gt 0)
            {
                $intuneAssignments += ConvertTo-IntunePolicyAssignment -Assignments $this.Assignments
            }
            foreach ($assignment in $intuneAssignments)
            {
                if ( $null -eq ($currentAssignments | Where-Object { $_.Target.groupId -eq $assignment.Target.groupId -and $_.Target.'@odata.type' -eq $assignment.Target.'@odata.type' }))
                {
                    New-MgBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment `
                        -WindowsAutopilotDeploymentProfileId $currentInstance.id `
                        -BodyParameter $assignment
                }
                else
                {
                    $currentAssignments = $currentAssignments | Where-Object { -not($_.Target.groupId -eq $assignment.Target.groupId -and $_.Target.'@odata.type' -eq $assignment.Target.'@odata.type') }
                }
            }
            if ($currentAssignments.Count -gt 0)
            {
                foreach ($assignment in $currentAssignments)
                {
                    Remove-MgBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment `
                        -WindowsAutopilotDeploymentProfileId $currentInstance.Id `
                        -WindowsAutopilotDeploymentProfileAssignmentId $assignment.Id
                }
            }
            #endregion
        }
        elseif ($this.Ensure -eq 'Absent' -and $currentInstance.Ensure -eq 'Present')
        {
            Write-Verbose -Message "Removing the Intune Windows Autopilot Deployment Profile Azure AD Joined with Id {$($currentInstance.Id)}"
            $currentAssignments = Get-MgBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment -WindowsAutopilotDeploymentProfileId $currentInstance.Id -All
            foreach ($assignment in $currentAssignments)
            {
                Remove-MgBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment `
                    -WindowsAutopilotDeploymentProfileId $currentInstance.Id `
                    -WindowsAutopilotDeploymentProfileAssignmentId $assignment.Id
            }
            #region resource generator code
            Remove-MgBetaDeviceManagementWindowsAutopilotDeploymentProfile -WindowsAutopilotDeploymentProfileId $currentInstance.Id
            #endregion
        }
    }

    [bool] Test()
    {
        return ([M365DSCResourceBase] $this).Test()
    }

    [string] Export()
    {
        if ($this.RequiresPowerShellCore())
        {
            return [string] $this.InvokeInPowerShellCore('Export')
        }

        $ConnectionMode = $this.Connect('MicrosoftGraph')

        #Ensure the proper dependencies are installed in the current environment.
        Confirm-M365DSCDependencies

        #region Telemetry
        $this.AddTelemetry('Export')
        #endregion

        try
        {
            #region resource generator code
            $baseFilter = "isof('microsoft.graph.azureADWindowsAutopilotDeploymentProfile')"
            $mergedFilter = $baseFilter
            if (-not [System.String]::IsNullOrEmpty($this.Filter))
            {
                $mergedFilter = "($baseFilter) and ($($this.Filter))"
            }
            [array]$getValue = Get-MgBetaDeviceManagementWindowsAutopilotDeploymentProfile -Filter $mergedFilter -All -ErrorAction Stop
            #endregion

            $i = 1
            $dscContent = [System.Text.StringBuilder]::new()
            if ($getValue.Length -eq 0)
            {
                Write-M365DSCHost -Message $Global:M365DSCEmojiGreenCheckMark -CommitWrite
            }
            else
            {
                Write-M365DSCHost -Message "`r`n" -DeferWrite
            }
            foreach ($config in $getValue)
            {
                if ($null -ne $Global:M365DSCExportResourceInstancesCount)
                {
                    $Global:M365DSCExportResourceInstancesCount++
                }

                $displayedKey = $config.Id
                if (-not [String]::IsNullOrEmpty($config.displayName))
                {
                    $displayedKey = $config.displayName
                }
                Write-M365DSCHost -Message "    |---[$i/$($getValue.Count)] $displayedKey" -DeferWrite
                $params = @{
                    Id                    = $config.Id
                    DisplayName           = $config.DisplayName
                    Ensure                = 'Present'
                    Credential            = $this.Credential
                    ApplicationId         = $this.ApplicationId
                    TenantId              = $this.TenantId
                    ApplicationSecret     = $this.ApplicationSecret
                    CertificateThumbprint = $this.CertificateThumbprint
                    CertificatePath       = $this.CertificatePath
                    CertificatePassword   = $this.CertificatePassword
                    ManagedIdentity       = $this.ManagedIdentity.IsPresent
                    AccessTokens          = $this.AccessTokens
                }

                $this.ExportedInstance = $config
                $Results = $this.GetForExport($Params)
                $rawResults = $Results.Clone()

                if ($null -ne $Results.EnrollmentStatusScreenSettings)
                {
                    $complexTypeStringResult = Get-M365DSCDRGComplexTypeToString `
                        -ComplexObject $Results.EnrollmentStatusScreenSettings `
                        -CIMInstanceName 'MicrosoftGraphwindowsEnrollmentStatusScreenSettings1'
                    if (-not [String]::IsNullOrWhiteSpace($complexTypeStringResult))
                    {
                        $Results.EnrollmentStatusScreenSettings = $complexTypeStringResult
                    }
                    else
                    {
                        $Results.Remove('EnrollmentStatusScreenSettings') | Out-Null
                    }
                }
                if ($null -ne $Results.OutOfBoxExperienceSetting)
                {
                    $complexTypeStringResult = Get-M365DSCDRGComplexTypeToString `
                        -ComplexObject $Results.OutOfBoxExperienceSetting `
                        -CIMInstanceName 'MicrosoftGraphoutOfBoxExperienceSetting'
                    if (-not [String]::IsNullOrWhiteSpace($complexTypeStringResult))
                    {
                        $Results.OutOfBoxExperienceSetting = $complexTypeStringResult
                    }
                    else
                    {
                        $Results.Remove('OutOfBoxExperienceSetting') | Out-Null
                    }
                }
                if ($Results.Assignments)
                {
                    $complexTypeStringResult = Get-M365DSCDRGComplexTypeToString -ComplexObject $Results.Assignments -CIMInstanceName DeviceManagementConfigurationPolicyAssignments
                    if ($complexTypeStringResult)
                    {
                        $Results.Assignments = $complexTypeStringResult
                    }
                    else
                    {
                        $Results.Remove('Assignments') | Out-Null
                    }
                }
                $currentDSCBlock = Get-M365DSCExportContentForResource -ResourceName $this.GetResourceName() `
                    -ConnectionMode $ConnectionMode `
                    -ModulePath $this.GetModulePath() `
                    -Results $Results `
                    -Credential $this.Credential `
                    -NoEscape @('EnrollmentStatusScreenSettings', 'OutOfBoxExperienceSetting', 'Assignments') `
                    -RawResults $rawResults

                [void]$dscContent.Append($currentDSCBlock)
                Save-M365DSCPartialExport -Content $currentDSCBlock `
                    -FileName $Global:PartialExportFileName
                $i++
                Write-M365DSCHost -Message $Global:M365DSCEmojiGreenCheckMark -CommitWrite
            }
            return $dscContent.ToString()
        }
        catch
        {
            if ($_.Exception -like '*401*' -or $_.ErrorDetails.Message -like "*`"ErrorCode`":`"Forbidden`"*" -or `
                    $_.Exception -like '*Request not applicable to target tenant*')
            {
                Write-M365DSCHost -Message "`r`n    $($Global:M365DSCEmojiYellowCircle) The current tenant is not registered for Intune."
            }
            else
            {
                $this.LogError($_, 'Error during Export:')

                throw
            }
        }

        # Every code path must return in a method with a declared return type.
        return ''
    }

    [System.Collections.Hashtable] GetCompareParameters()
    {
        return @{
            ExcludedProperties = @('DeviceType')
        }
    }

    hidden [IntuneWindowsAutopilotDeploymentProfileAzureADJoined] AsResult([System.Object] $Values)
    {
        if ($Values -is [IntuneWindowsAutopilotDeploymentProfileAzureADJoined])
        {
            return $Values
        }

        $result = [IntuneWindowsAutopilotDeploymentProfileAzureADJoined]::new()
        $result.ClearNonSchemaProperties()
        if ($Values -is [System.Collections.Hashtable])
        {
            $result.FromHashtable($Values)
        }

        return $result
    }
}

class MSFT_MicrosoftGraphwindowsEnrollmentStatusScreenSettings1
{
    [DscProperty()]
    [System.ComponentModel.Description('Allow or block user to use device before profile and app installation complete')]
    [System.Nullable[System.Boolean]] $AllowDeviceUseBeforeProfileAndAppInstallComplete

    [DscProperty()]
    [System.ComponentModel.Description('Allow the user to continue using the device on installation failure')]
    [System.Nullable[System.Boolean]] $AllowDeviceUseOnInstallFailure

    [DscProperty()]
    [System.ComponentModel.Description('Allow or block log collection on installation failure')]
    [System.Nullable[System.Boolean]] $AllowLogCollectionOnInstallFailure

    [DscProperty()]
    [System.ComponentModel.Description('Allow the user to retry the setup on installation failure')]
    [System.Nullable[System.Boolean]] $BlockDeviceSetupRetryByUser

    [DscProperty()]
    [System.ComponentModel.Description('Set custom error message to show upon installation failure')]
    [System.String] $CustomErrorMessage

    [DscProperty()]
    [System.ComponentModel.Description('Show or hide installation progress to user')]
    [System.Nullable[System.Boolean]] $HideInstallationProgress

    [DscProperty()]
    [System.ComponentModel.Description('Set installation progress timeout in minutes')]
    [System.Nullable[System.UInt32]] $InstallProgressTimeoutInMinutes
}

class MSFT_MicrosoftGraphoutOfBoxExperienceSetting
{
    [DscProperty()]
    [System.ComponentModel.Description('AAD join authentication type. Possible values are: shared, singleUser.')]
    [ValidateSet('shared', 'singleUser')]
    [System.String] $DeviceUsageType

    [DscProperty()]
    [System.ComponentModel.Description('If set to true, then the user can''t start over with different account, on company sign-in')]
    [System.Nullable[System.Boolean]] $EscapeLinkHidden

    [DscProperty()]
    [System.ComponentModel.Description('Show or hide EULA to user')]
    [System.Nullable[System.Boolean]] $EulaHidden

    [DscProperty()]
    [System.ComponentModel.Description('If set, then skip the keyboard selection page if Language and Region are set')]
    [System.Nullable[System.Boolean]] $KeyboardSelectionPageSkipped

    [DscProperty()]
    [System.ComponentModel.Description('Show or hide privacy settings to user')]
    [System.Nullable[System.Boolean]] $PrivacySettingsHidden

    [DscProperty()]
    [System.ComponentModel.Description('Type of user. Possible values are: administrator, standard.')]
    [ValidateSet('administrator', 'standard')]
    [System.String] $UserType
}

class MSFT_DeviceManagementConfigurationPolicyAssignments
{
    [DscProperty(Mandatory)]
    [System.ComponentModel.Description('The type of the target assignment.')]
    [ValidateSet('#microsoft.graph.cloudPcManagementGroupAssignmentTarget', '#microsoft.graph.groupAssignmentTarget', '#microsoft.graph.allLicensedUsersAssignmentTarget', '#microsoft.graph.allDevicesAssignmentTarget', '#microsoft.graph.exclusionGroupAssignmentTarget', '#microsoft.graph.configurationManagerCollectionAssignmentTarget')]
    [System.String] $dataType

    [DscProperty()]
    [System.ComponentModel.Description('The type of filter of the target assignment i.e. Exclude or Include. Possible values are:none, include, exclude.')]
    [ValidateSet('none', 'include', 'exclude')]
    [System.String] $deviceAndAppManagementAssignmentFilterType

    [DscProperty()]
    [System.ComponentModel.Description('The Id of the filter for the target assignment.')]
    [System.String] $deviceAndAppManagementAssignmentFilterId

    [DscProperty()]
    [System.ComponentModel.Description('The display name of the filter for the target assignment.')]
    [System.String] $deviceAndAppManagementAssignmentFilterDisplayName

    [DscProperty()]
    [System.ComponentModel.Description('The group Id that is the target of the assignment.')]
    [System.String] $groupId

    [DscProperty()]
    [System.ComponentModel.Description('The group Display Name that is the target of the assignment.')]
    [System.String] $groupDisplayName

    [DscProperty()]
    [System.ComponentModel.Description('The collection Id that is the target of the assignment.(ConfigMgr)')]
    [System.String] $collectionId
}
