using module ..\_Base\M365DSCResourceBase.psm1

[DscResource()]
class EXORemoteDomain : M365DSCResourceBase
{
    [DscProperty(Key)]
    [System.ComponentModel.Description('Specify the Identity for the RemoteDomain.')]
    [System.String] $Identity

    [DscProperty()]
    [System.ComponentModel.Description('The DomainName parameter specifies the SMTP domain that you want to establish as a remote domain. A valid value is an SMTP domain (for example, contoso.com). The maximum length is 256 characters.')]
    [ValidateLength(0, 256)]
    [System.String] $DomainName

    [DscProperty()]
    [System.ComponentModel.Description('Specify if the RemoteDomain should exist or not.')]
    [ValidateSet('Present', 'Absent')]
    [System.String] $Ensure

    [DscProperty()]
    [System.ComponentModel.Description('The AllowedOOFType parameter specifies the type of automatic replies or out-of-office (also known as OOF) notifications than can be sent to recipients in the remote domain. Valid values are: External, ExternalLegacy, InternalLegacy or None')]
    [ValidateSet('External', 'ExternalLegacy', 'InternalLegacy', 'None')]
    [System.String] $AllowedOOFType

    [DscProperty()]
    [System.ComponentModel.Description('The AutoForwardEnabled parameter specifies whether to allow messages that are auto-forwarded by client email programs in your organization.')]
    [System.Nullable[System.Boolean]] $AutoForwardEnabled

    [DscProperty()]
    [System.ComponentModel.Description('The AutoReplyEnabled parameter specifies whether to allow messages that are automatic replies from client email programs in your organization (for example, automatic reply messages that are generated by rules in Outlook).')]
    [System.Nullable[System.Boolean]] $AutoReplyEnabled

    [DscProperty()]
    [System.ComponentModel.Description('The ByteEncoderTypeFor7BitCharsets parameter specifies the 7-bit transfer encoding method for MIME format for messages sent to this remote domain.')]
    [ValidateSet('Use7Bit', 'UseQP', 'UseBase64', 'UseQPHtmlDetectTextPlain', 'UseBase64HtmlDetectTextPlain', 'UseQPHtml7BitTextPlain', 'UseBase64Html7BitTextPlain', 'Undefined')]
    [System.String] $ByteEncoderTypeFor7BitCharsets

    [DscProperty()]
    [System.ComponentModel.Description('The CharacterSet parameter specifies a character set for MIME messages without defined character sets that are sent from your organization to recipients in the remote domain.')]
    [System.String] $CharacterSet

    [DscProperty()]
    [System.ComponentModel.Description('The ContentType parameter specifies the outbound message content type and formatting.')]
    [ValidateSet('MimeHtmlText', 'MimeText', 'MimeHtml')]
    [System.String] $ContentType

    [DscProperty()]
    [System.ComponentModel.Description('The DeliveryReportEnabled parameter specifies whether to allow delivery reports from client software in your organization to recipients in the remote domain.')]
    [System.Nullable[System.Boolean]] $DeliveryReportEnabled

    [DscProperty()]
    [System.ComponentModel.Description('The DisplaySenderName parameter specifies whether to show the sender''s Display Name in the From email address for messages sent to recipients in the remote domain.')]
    [System.Nullable[System.Boolean]] $DisplaySenderName

    [DscProperty()]
    [System.ComponentModel.Description('The IsInternal parameter specifies whether the recipients in the remote domain are considered to be internal recipients.')]
    [System.Nullable[System.Boolean]] $IsInternal

    [DscProperty()]
    [System.ComponentModel.Description('The LineWrapSize parameter specifies the line-wrap size for messages to recipients in the remote domain. Valid values are an integer from 0 through 132 or the value to unlimited. The default value is unlimited.')]
    [System.String] $LineWrapSize

    [DscProperty()]
    [System.ComponentModel.Description('The MeetingForwardNotificationEnabled parameter specifies whether to enable meeting forward notifications for recipients in the remote domain.')]
    [System.Nullable[System.Boolean]] $MeetingForwardNotificationEnabled

    [DscProperty()]
    [System.ComponentModel.Description('The Name parameter specifies a unique name for the remote domain object. The maximum length is 64 characters. If the value contains spaces, enclose the value in quotation marks.')]
    [ValidateLength(1, 64)]
    [System.String] $Name

    [DscProperty()]
    [System.ComponentModel.Description('The NDREnabled parameter specifies whether to allow non-delivery reports (also known NDRs or bounce messages) from your organization to recipients in the remote domain.')]
    [System.Nullable[System.Boolean]] $NDREnabled

    [DscProperty()]
    [System.ComponentModel.Description('The NonMimeCharacterSet parameter specifies a character set for plain text messages without defined character sets that are sent from your organization to recipients in the remote domain.')]
    [System.String] $NonMimeCharacterSet

    [DscProperty()]
    [System.ComponentModel.Description('The PreferredInternetCodePageForShiftJis parameter specifies the specific code page to use for Shift JIS character encoding in messages that are sent to recipients in the remote domain.')]
    [ValidateSet('50220', '50221', '50222', 'Undefined')]
    [System.String] $PreferredInternetCodePageForShiftJis

    [DscProperty()]
    [System.ComponentModel.Description('The RequiredCharsetCoverage parameter specifies a percentage threshold for characters in a message that must match to apply your organization''s preferred character set before switching to automatic character set detection.')]
    [System.Nullable[System.Int32]] $RequiredCharsetCoverage

    [DscProperty()]
    [System.ComponentModel.Description('The TargetDeliveryDomain parameter specifies whether the remote domain is used in cross-forest deployments to generate target email addresses for new mail users that represent users in the other organization (for example, all mailboxes hosted on Exchange Online are represented as mail users in your on-premises organization).')]
    [System.Nullable[System.Boolean]] $TargetDeliveryDomain

    [DscProperty()]
    [System.ComponentModel.Description('The TNEFEnabled parameter specifies whether Transport Neutral Encapsulation Format (TNEF) message encoding is used on messages sent to the remote domain.')]
    [System.Nullable[System.Boolean]] $TNEFEnabled

    [DscProperty()]
    [System.ComponentModel.Description('The TrustedMailInboundEnabled parameter specifies whether messages from senders in the remote domain are treated as trusted messages.')]
    [System.Nullable[System.Boolean]] $TrustedMailInboundEnabled

    [DscProperty()]
    [System.ComponentModel.Description('The TrustedMailOutboundEnabled parameter specifies whether messages sent to recipients in the remote domain are treated as trusted messages.')]
    [System.Nullable[System.Boolean]] $TrustedMailOutboundEnabled

    [DscProperty()]
    [System.ComponentModel.Description('The UseSimpleDisplayName parameter specifies whether the sender''s simple display name is used for the From email address in messages sent to recipients in the remote domain.')]
    [System.Nullable[System.Boolean]] $UseSimpleDisplayName

    [DscProperty()]
    [System.ComponentModel.Description('Credentials of the Exchange Global Admin')]
    [System.Management.Automation.PSCredential] $Credential

    [DscProperty()]
    [System.ComponentModel.Description('Id of the Azure Active Directory application to authenticate with.')]
    [System.String] $ApplicationId

    [DscProperty()]
    [System.ComponentModel.Description('Id of the Azure Active Directory tenant used for authentication.')]
    [System.String] $TenantId

    [DscProperty()]
    [System.ComponentModel.Description('Thumbprint of the Azure Active Directory application''s authentication certificate to use for authentication.')]
    [System.String] $CertificateThumbprint

    [DscProperty()]
    [System.ComponentModel.Description('Username can be made up to anything but password will be used for CertificatePassword')]
    [System.Management.Automation.PSCredential] $CertificatePassword

    [DscProperty()]
    [System.ComponentModel.Description('Path to certificate used in service principal usually a PFX file.')]
    [System.String] $CertificatePath

    [DscProperty()]
    [System.ComponentModel.Description('Managed ID being used for authentication.')]
    [System.Nullable[System.Boolean]] $ManagedIdentity

    [DscProperty()]
    [System.ComponentModel.Description('Access token used for authentication.')]
    [System.String[]] $AccessTokens

    [EXORemoteDomain] Get()
    {
        if ($this.RequiresPowerShellCore())
        {
            $remote = [EXORemoteDomain]::new()
            $remote.FromHashtable($this.InvokeInPowerShellCore('Get'))
            return $remote
        }

        Write-Verbose -Message "Getting configuration of Remote Domain for $($this.Identity)"

        try
        {
            if (-not $this.ExportedInstance -or $this.ExportedInstance.Identity -ne $this.Identity)
            {
                $null = $this.Connect('ExchangeOnline')

                Confirm-M365DSCDependencies

                $this.AddTelemetry('Get')

                $nullReturn = $this.GetBoundParameters()
                $nullReturn.Ensure = 'Absent'

                $RemoteDomain = Get-RemoteDomain -Identity $this.Identity -ErrorAction SilentlyContinue
                if ($null -eq $RemoteDomain)
                {
                    Write-Verbose -Message "RemoteDomain configuration for $($this.Identity) does not exist."
                    return $this.AsResult($nullReturn)
                }
            }
            else
            {
                $RemoteDomain = $this.ExportedInstance
            }

            Write-Verbose -Message "Found RemoteDomain with Identity {$($this.Identity)}"

            $result = @{
                Identity                             = $RemoteDomain.Identity
                DomainName                           = $RemoteDomain.DomainName
                AllowedOOFType                       = $RemoteDomain.AllowedOOFType
                Ensure                               = 'Present'
                AutoForwardEnabled                   = $RemoteDomain.AutoForwardEnabled
                AutoReplyEnabled                     = $RemoteDomain.AutoReplyEnabled
                ByteEncoderTypeFor7BitCharsets       = $RemoteDomain.ByteEncoderTypeFor7BitCharsets
                CharacterSet                         = $RemoteDomain.CharacterSet
                ContentType                          = $RemoteDomain.ContentType
                DeliveryReportEnabled                = $RemoteDomain.DeliveryReportEnabled
                DisplaySenderName                    = $RemoteDomain.DisplaySenderName
                IsInternal                           = $RemoteDomain.IsInternal
                LineWrapSize                         = $RemoteDomain.LineWrapSize
                MeetingForwardNotificationEnabled    = $RemoteDomain.MeetingForwardNotificationEnabled
                Name                                 = $RemoteDomain.Name
                NDREnabled                           = $RemoteDomain.NDREnabled
                NonMimeCharacterSet                  = $RemoteDomain.NonMimeCharacterSet
                PreferredInternetCodePageForShiftJis = $RemoteDomain.PreferredInternetCodePageForShiftJis
                RequiredCharsetCoverage              = $RemoteDomain.RequiredCharsetCoverage
                TargetDeliveryDomain                 = $RemoteDomain.TargetDeliveryDomain
                TNEFEnabled                          = $RemoteDomain.TNEFEnabled
                TrustedMailInboundEnabled            = $RemoteDomain.TrustedMailInboundEnabled
                TrustedMailOutboundEnabled           = $RemoteDomain.TrustedMailOutboundEnabled
                UseSimpleDisplayName                 = $RemoteDomain.UseSimpleDisplayName
                Credential                           = $this.Credential
                ApplicationId                        = $this.ApplicationId
                CertificateThumbprint                = $this.CertificateThumbprint
                CertificatePath                      = $this.CertificatePath
                CertificatePassword                  = $this.CertificatePassword
                ManagedIdentity                      = $this.ManagedIdentity.IsPresent
                TenantId                             = $this.TenantId
                AccessTokens                         = $this.AccessTokens
            }

            return $this.AsResult($result)
        }
        catch
        {
            $this.LogError($_, 'Error retrieving data:')

            throw
        }
    }

    [void] Set()
    {
        if ($this.RequiresPowerShellCore())
        {
            $null = $this.InvokeInPowerShellCore('Set')
            return
        }

        Confirm-M365DSCDependencies

        $this.AddTelemetry('Set')
        Write-Verbose -Message "Setting configuration of Remote Domain for $($this.Identity)"

        $currentRemoteDomainConfig = $this.Get().ToHashtable()

        $null = $this.Connect('ExchangeOnline')

        $RemoteDomainParams = Remove-M365DSCAuthenticationParameter -BoundParameters $this.GetBoundParameters()

        # CASE: Remote Domain doesn't exist but should;
        if ($this.Ensure -eq 'Present' -and $currentRemoteDomainConfig.Ensure -eq 'Absent')
        {
            Write-Verbose -Message "Remote Domain '$($this.Name)' does not exist but it should. Create and configure it."
            # Create remote domain
            $remoteDomainName = $this.Name
            if ([System.String]::IsNullOrEmpty($remoteDomainName))
            {
                $remoteDomainName = $this.Identity
            }
            New-RemoteDomain -Name $remoteDomainName -DomainName $this.DomainName

            $tries = 1
            $remoteDomain = $null
            do
            {
                Write-Verbose -Message 'Waiting for 10 seconds'
                Start-Sleep -Seconds 10
                $remoteDomain = Get-RemoteDomain -Identity $remoteDomainName -ErrorAction SilentlyContinue
                $tries++
            } until ($null -eq $remoteDomain -or $tries -le 12)

            # Configure new remote domain
            $RemoteDomainParams.Remove('DomainName') | Out-Null
            Set-RemoteDomain @RemoteDomainParams
        }
        # CASE: Remote Domain exists but it shouldn't;
        elseif ($this.Ensure -eq 'Absent' -and $currentRemoteDomainConfig.Ensure -eq 'Present')
        {
            Write-Verbose -Message "Remote Domain '$($this.Name)' exists but it shouldn't. Remove it."
            Remove-RemoteDomain -Identity $this.Name -Confirm:$false
        }
        # CASE: Remote Domain exists and it should, but has different values than the desired ones
        elseif ($this.Ensure -eq 'Present' -and $currentRemoteDomainConfig.Ensure -eq 'Present')
        {
            Write-Verbose -Message "Remote Domain '$($this.Name)' already exists, but needs updating."
            Write-Verbose -Message "Setting RemoteDomain for $($this.Identity) with values: $(Convert-M365DscHashtableToString -Hashtable $RemoteDomainParams)"
            $RemoteDomainParams.Remove('DomainName') | Out-Null
            Set-RemoteDomain @RemoteDomainParams
        }
    }

    [bool] Test()
    {
        return ([M365DSCResourceBase] $this).Test()
    }

    [string] Export()
    {
        if ($this.RequiresPowerShellCore())
        {
            return [string] $this.InvokeInPowerShellCore('Export')
        }

        $ConnectionMode = $this.Connect('ExchangeOnline')

        Confirm-M365DSCDependencies

        $this.AddTelemetry('Export')

        try
        {
            [array]$AllRemoteDomains = Get-RemoteDomain -ErrorAction Stop

            $dscContent = [System.Text.StringBuilder]::new()

            if ($AllRemoteDomains.Length -eq 0)
            {
                Write-M365DSCHost -Message $Global:M365DSCEmojiGreenCheckMark -CommitWrite
            }
            else
            {
                Write-M365DSCHost -Message "`r`n" -DeferWrite
            }
            $i = 1
            foreach ($domain in $AllRemoteDomains)
            {
                if ($null -ne $Global:M365DSCExportResourceInstancesCount)
                {
                    $Global:M365DSCExportResourceInstancesCount++
                }

                Write-M365DSCHost -Message "    |---[$i/$($AllRemoteDomains.Length)] $($domain.Identity)" -DeferWrite

                $Params = @{
                    Identity              = $domain.Identity
                    Credential            = $this.Credential
                    ApplicationId         = $this.ApplicationId
                    TenantId              = $this.TenantId
                    CertificateThumbprint = $this.CertificateThumbprint
                    CertificatePassword   = $this.CertificatePassword
                    ManagedIdentity       = $this.ManagedIdentity.IsPresent
                    CertificatePath       = $this.CertificatePath
                    AccessTokens          = $this.AccessTokens
                }
                $this.ExportedInstance = $domain
                $Results = $this.GetForExport($Params)
                $currentDSCBlock = Get-M365DSCExportContentForResource -ResourceName $this.GetResourceName() `
                    -ConnectionMode $ConnectionMode `
                    -ModulePath $this.GetModulePath() `
                    -Results $Results `
                    -Credential $this.Credential
                [void]$dscContent.Append($currentDSCBlock)
                Save-M365DSCPartialExport -Content $currentDSCBlock `
                    -FileName $Global:PartialExportFileName
                Write-M365DSCHost -Message $Global:M365DSCEmojiGreenCheckMark -CommitWrite
                $i++
            }
            return $dscContent.ToString()
        }
        catch
        {
            $this.LogError($_, 'Error during Export:')

            throw
        }
    }

    hidden [EXORemoteDomain] AsResult([System.Object] $Values)
    {
        if ($Values -is [EXORemoteDomain])
        {
            return $Values
        }

        $result = [EXORemoteDomain]::new()
        $result.ClearNonSchemaProperties()
        if ($Values -is [System.Collections.Hashtable])
        {
            $result.FromHashtable($Values)
        }

        return $result
    }
}
