using module ..\_Base\M365DSCResourceBase.psm1

[DscResource()]
class AADAuthenticationMethodPolicyAuthenticator : M365DSCResourceBase
{
    [DscProperty()]
    [System.ComponentModel.Description('A collection of Microsoft Authenticator settings such as number matching and location context, and whether they are enabled for all users or specific users only.')]
    [MSFT_MicrosoftGraphMicrosoftAuthenticatorFeatureSettings] $FeatureSettings

    [DscProperty()]
    [System.ComponentModel.Description('true if users can use the OTP code generated by the Microsoft Authenticator app, false otherwise.')]
    [System.Nullable[System.Boolean]] $IsSoftwareOathEnabled

    [DscProperty()]
    [System.ComponentModel.Description('Displayname of the groups of users that are excluded from a policy.')]
    [MSFT_AADAuthenticationMethodPolicyAuthenticatorExcludeTarget[]] $ExcludeTargets

    [DscProperty()]
    [System.ComponentModel.Description('Displayname of the groups of users that are included from a policy.')]
    [MSFT_AADAuthenticationMethodPolicyAuthenticatorIncludeTarget[]] $IncludeTargets

    [DscProperty()]
    [System.ComponentModel.Description('The state of the policy. Possible values are: enabled, disabled.')]
    [ValidateSet('enabled', 'disabled')]
    [System.String] $State

    [DscProperty(Key)]
    [System.ComponentModel.Description('The unique identifier for an entity. Read-only.')]
    [System.String] $Id

    [DscProperty()]
    [System.ComponentModel.Description('Present ensures the policy exists, absent ensures it is removed.')]
    [ValidateSet('Present', 'Absent')]
    [System.String] $Ensure

    [DscProperty()]
    [System.ComponentModel.Description('Credentials of the Admin')]
    [System.Management.Automation.PSCredential] $Credential

    [DscProperty()]
    [System.ComponentModel.Description('Id of the Azure Active Directory application to authenticate with.')]
    [System.String] $ApplicationId

    [DscProperty()]
    [System.ComponentModel.Description('Id of the Azure Active Directory tenant used for authentication.')]
    [System.String] $TenantId

    [DscProperty()]
    [System.ComponentModel.Description('Secret of the Azure Active Directory tenant used for authentication.')]
    [System.Management.Automation.PSCredential] $ApplicationSecret

    [DscProperty()]
    [System.ComponentModel.Description('Thumbprint of the Azure Active Directory application''s authentication certificate to use for authentication.')]
    [System.String] $CertificateThumbprint

    [DscProperty()]
    [System.ComponentModel.Description('Username can be made up to anything but password will be used for CertificatePassword')]
    [System.Management.Automation.PSCredential] $CertificatePassword

    [DscProperty()]
    [System.ComponentModel.Description('Path to certificate used in service principal usually a PFX file.')]
    [System.String] $CertificatePath

    [DscProperty()]
    [System.ComponentModel.Description('Managed ID being used for authentication.')]
    [System.Nullable[System.Boolean]] $ManagedIdentity

    [DscProperty()]
    [System.ComponentModel.Description('Access token used for authentication.')]
    [System.String[]] $AccessTokens

    [AADAuthenticationMethodPolicyAuthenticator] Get()
    {
        if ($this.RequiresPowerShellCore())
        {
            $remote = [AADAuthenticationMethodPolicyAuthenticator]::new()
            $remote.FromHashtable($this.InvokeInPowerShellCore('Get'))
            return $remote
        }

        Write-Verbose -Message "Getting the Azure AD Authentication Method Policy with Id {$($this.Id)}"

        try
        {
            if (-not $this.ExportedInstance -or $this.ExportedInstance.Id -ne $this.Id)
            {
                $null = $this.Connect('MicrosoftGraph')

                Confirm-M365DSCDependencies

                $this.AddTelemetry('Get')

                $nullResult = $this.GetBoundParameters()
                $nullResult.Ensure = 'Absent'

                $getValue = $null
                #region resource generator code
                $getValue = Get-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration -AuthenticationMethodConfigurationId $this.Id -ErrorAction SilentlyContinue

                #endregion
                if ($null -eq $getValue)
                {
                    Write-Verbose -Message "Could not find an Azure AD Authentication Method Policy Authenticator with id {$($this.id)}"
                    return $this.AsResult($nullResult)
                }
            }
            else
            {
                $getValue = $this.ExportedInstance
            }
            $resolvedId = $getValue.Id
            Write-Verbose -Message "An Azure AD Authentication Method Policy Authenticator with Id {$($resolvedId)} was found."

            #region resource generator code
            $complexFeatureSettings = [ordered]@{}

            Write-Verbose 'Processing FeatureSettings > companionAppAllowedState > excludeTarget'
            $complexCompanionAppAllowedState = [ordered]@{}
            $complexExcludeTarget = [ordered]@{}
            if ($getValue.featureSettings.companionAppAllowedState.excludeTarget.id -notmatch 'all_users|00000000-0000-0000-0000-000000000000')
            {
                $myExcludeTargetsDisplayName = Get-M365DSCGroupDisplayNameById -GroupId $getValue.featureSettings.companionAppAllowedState.excludeTarget.id
                if ($null -eq $myExcludeTargetsDisplayName)
                {
                    continue
                }
                $complexExcludeTarget.Add('Id', $myExcludeTargetsDisplayName)
            }
            else
            {
                if ($getValue.featureSettings.companionAppAllowedState.excludeTarget.id -eq '00000000-0000-0000-0000-000000000000')
                {
                    $complexExcludeTarget.Add('Id', '00000000-0000-0000-0000-000000000000')
                }
                else
                {
                    $complexExcludeTarget.Add('Id', 'all_users')
                }
            }

            if ($null -ne $getValue.featureSettings.companionAppAllowedState.excludeTarget.targetType)
            {
                $complexExcludeTarget.Add('TargetType', $getValue.featureSettings.companionAppAllowedState.excludeTarget.targetType.ToString())
            }

            if ($complexExcludeTarget.values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexExcludeTarget = $null
            }
            $complexCompanionAppAllowedState.Add('ExcludeTarget', $complexExcludeTarget)

            Write-Verbose 'Processing FeatureSettings > companionAppAllowedState > includeTarget'
            $complexIncludeTarget = [ordered]@{}
            if ($getValue.featureSettings.companionAppAllowedState.includeTarget.id -notmatch 'all_users|00000000-0000-0000-0000-000000000000')
            {
                $myIncludeTargetsDisplayName = Get-M365DSCGroupDisplayNameById -GroupId $getValue.featureSettings.companionAppAllowedState.includeTarget.id
                if ($null -eq $myIncludeTargetsDisplayName)
                {
                    continue
                }
                $complexIncludeTarget.Add('Id', $myIncludeTargetsDisplayName)
            }
            else
            {
                if ($getValue.featureSettings.companionAppAllowedState.includeTarget.id -eq '00000000-0000-0000-0000-000000000000')
                {
                    $complexIncludeTarget.Add('Id', '00000000-0000-0000-0000-000000000000')
                }
                else
                {
                    $complexIncludeTarget.Add('Id', 'all_users')
                }
            }

            if ($null -ne $getValue.featureSettings.companionAppAllowedState.includeTarget.targetType)
            {
                $complexIncludeTarget.Add('TargetType', $getValue.featureSettings.companionAppAllowedState.includeTarget.targetType.ToString())
            }

            if ($complexIncludeTarget.values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexIncludeTarget = $null
            }
            $complexCompanionAppAllowedState.Add('IncludeTarget', $complexIncludeTarget)

            Write-Verbose 'Processing FeatureSettings > companionAppAllowedState > state'
            if ($null -ne $getValue.featureSettings.companionAppAllowedState.state)
            {
                $complexCompanionAppAllowedState.Add('State', $getValue.featureSettings.companionAppAllowedState.state.ToString())
            }

            if ($complexCompanionAppAllowedState.values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexCompanionAppAllowedState = $null
            }

            $complexFeatureSettings.Add('CompanionAppAllowedState', $complexCompanionAppAllowedState)
            $complexDisplayAppInformationRequiredState = [ordered]@{}

            Write-Verbose 'Processing FeatureSettings > displayAppInformationRequiredState > excludeTarget'
            $complexExcludeTarget = [ordered]@{}
            if ($getValue.featureSettings.displayAppInformationRequiredState.excludeTarget.id -notmatch 'all_users|00000000-0000-0000-0000-000000000000')
            {
                $myExcludeTargetsDisplayName = Get-M365DSCGroupDisplayNameById -GroupId $getValue.featureSettings.displayAppInformationRequiredState.excludeTarget.id
                if ($null -eq $myExcludeTargetsDisplayName)
                {
                    continue
                }
                $complexExcludeTarget.Add('Id', $myExcludeTargetsDisplayName)
            }
            else
            {
                if ($getValue.featureSettings.displayAppInformationRequiredState.excludeTarget.id -eq '00000000-0000-0000-0000-000000000000')
                {
                    $complexExcludeTarget.Add('Id', '00000000-0000-0000-0000-000000000000')
                }
                else
                {
                    $complexExcludeTarget.Add('Id', 'all_users')
                }
            }

            if ($null -ne $getValue.featureSettings.displayAppInformationRequiredState.excludeTarget.targetType)
            {
                $complexExcludeTarget.Add('TargetType', $getValue.featureSettings.displayAppInformationRequiredState.excludeTarget.targetType.ToString())
            }
            if ($complexExcludeTarget.values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexExcludeTarget = $null
            }
            $complexDisplayAppInformationRequiredState.Add('ExcludeTarget', $complexExcludeTarget)

            Write-Verbose 'Processing FeatureSettings > displayAppInformationRequiredState > includeTarget'
            $complexIncludeTarget = [ordered]@{}
            if ($getValue.featureSettings.displayAppInformationRequiredState.includeTarget.id -notmatch 'all_users|00000000-0000-0000-0000-000000000000')
            {
                $myIncludeTargetsDisplayName = Get-M365DSCGroupDisplayNameById -GroupId $getValue.featureSettings.displayAppInformationRequiredState.includeTarget.id
                if ($null -eq $myIncludeTargetsDisplayName)
                {
                    continue
                }
                $complexIncludeTarget.Add('Id', $myIncludeTargetsDisplayName)
            }
            else
            {
                if ($getValue.featureSettings.displayAppInformationRequiredState.includeTarget.id -eq '00000000-0000-0000-0000-000000000000')
                {
                    $complexIncludeTarget.Add('Id', '00000000-0000-0000-0000-000000000000')
                }
                else
                {
                    $complexIncludeTarget.Add('Id', 'all_users')
                }
            }

            if ($null -ne $getValue.featureSettings.displayAppInformationRequiredState.includeTarget.targetType)
            {
                $complexIncludeTarget.Add('TargetType', $getValue.featureSettings.displayAppInformationRequiredState.includeTarget.targetType.ToString())
            }

            if ($complexIncludeTarget.values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexIncludeTarget = $null
            }
            $complexDisplayAppInformationRequiredState.Add('IncludeTarget', $complexIncludeTarget)

            Write-Verbose 'Processing FeatureSettings > displayAppInformationRequiredState > state'
            if ($null -ne $getValue.featureSettings.displayAppInformationRequiredState.state)
            {
                $complexDisplayAppInformationRequiredState.Add('State', $getValue.featureSettings.displayAppInformationRequiredState.state.ToString())
            }

            if ($complexDisplayAppInformationRequiredState.values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexDisplayAppInformationRequiredState = $null
            }

            $complexFeatureSettings.Add('DisplayAppInformationRequiredState', $complexDisplayAppInformationRequiredState)

            Write-Verbose 'Processing FeatureSettings > displayLocationInformationRequiredState > excludeTarget'
            $complexDisplayLocationInformationRequiredState = [ordered]@{}
            $complexExcludeTarget = [ordered]@{}
            if ($getValue.featureSettings.displayLocationInformationRequiredState.excludeTarget.id -notmatch 'all_users|00000000-0000-0000-0000-000000000000')
            {
                $myExcludeTargetsDisplayName = Get-M365DSCGroupDisplayNameById -GroupId $getValue.featureSettings.displayLocationInformationRequiredState.excludeTarget.id
                if ($null -eq $myExcludeTargetsDisplayName)
                {
                    continue
                }
                $complexExcludeTarget.Add('Id', $myExcludeTargetsDisplayName)
            }
            else
            {
                if ($getValue.featureSettings.displayLocationInformationRequiredState.excludeTarget.id -eq '00000000-0000-0000-0000-000000000000')
                {
                    $complexExcludeTarget.Add('Id', '00000000-0000-0000-0000-000000000000')
                }
                else
                {
                    $complexExcludeTarget.Add('Id', 'all_users')
                }
            }

            if ($null -ne $getValue.featureSettings.displayLocationInformationRequiredState.excludeTarget.targetType)
            {
                $complexExcludeTarget.Add('TargetType', $getValue.featureSettings.displayLocationInformationRequiredState.excludeTarget.targetType.ToString())
            }

            if ($complexExcludeTarget.values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexExcludeTarget = $null
            }

            $complexDisplayLocationInformationRequiredState.Add('ExcludeTarget', $complexExcludeTarget)

            Write-Verbose 'Processing FeatureSettings > displayLocationInformationRequiredState > includeTarget'
            $complexIncludeTarget = [ordered]@{}
            if ($getValue.featureSettings.displayLocationInformationRequiredState.includeTarget.id -notmatch 'all_users|00000000-0000-0000-0000-000000000000')
            {
                $myIncludeTargetsDisplayName = Get-M365DSCGroupDisplayNameById -GroupId $getValue.featureSettings.displayLocationInformationRequiredState.includeTarget.id
                if ($null -eq $myIncludeTargetsDisplayName)
                {
                    continue
                }
                $complexIncludeTarget.Add('Id', $myIncludeTargetsDisplayName)
            }
            else
            {
                if ($getValue.featureSettings.displayLocationInformationRequiredState.includeTarget.id -eq '00000000-0000-0000-0000-000000000000')
                {
                    $complexIncludeTarget.Add('Id', '00000000-0000-0000-0000-000000000000')
                }
                else
                {
                    $complexIncludeTarget.Add('Id', 'all_users')
                }
            }

            if ($null -ne $getValue.featureSettings.displayLocationInformationRequiredState.includeTarget.targetType)
            {
                $complexIncludeTarget.Add('TargetType', $getValue.featureSettings.displayLocationInformationRequiredState.includeTarget.targetType.ToString())
            }

            if ($complexIncludeTarget.values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexIncludeTarget = $null
            }

            $complexDisplayLocationInformationRequiredState.Add('IncludeTarget', $complexIncludeTarget)

            Write-Verbose 'Processing FeatureSettings > displayLocationInformationRequiredState > state'
            if ($null -ne $getValue.featureSettings.displayLocationInformationRequiredState.state)
            {
                $complexDisplayLocationInformationRequiredState.Add('State', $getValue.featureSettings.displayLocationInformationRequiredState.state.ToString())
            }

            if ($complexDisplayLocationInformationRequiredState.values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexDisplayLocationInformationRequiredState = $null
            }

            $complexFeatureSettings.Add('DisplayLocationInformationRequiredState', $complexDisplayLocationInformationRequiredState)

            $complexExcludeTargets = @()
            foreach ($currentExcludeTargets in $getValue.ExcludeTargets)
            {
                $myExcludeTargets = [ordered]@{}
                if ($currentExcludeTargets.id -ne 'all_users')
                {
                    $myExcludeTargetsDisplayName = Get-M365DSCGroupDisplayNameById -GroupId $currentExcludeTargets.id
                    if ($null -eq $myExcludeTargetsDisplayName)
                    {
                        continue
                    }
                    $myExcludeTargets.Add('Id', $myExcludeTargetsDisplayName)
                }
                else
                {
                    $myExcludeTargets.Add('Id', $currentExcludeTargets.id)
                }

                if ($null -ne $currentExcludeTargets.targetType)
                {
                    $myExcludeTargets.Add('TargetType', $currentExcludeTargets.targetType.ToString())
                }

                if ($myExcludeTargets.values.Where({ $null -ne $_ }).Count -gt 0)
                {
                    $complexExcludeTargets += $myExcludeTargets
                }
            }
            #endregion

            $complexIncludeTargets = @()
            foreach ($currentIncludeTargets in $getValue.includeTargets)
            {
                $myIncludeTargets = [ordered]@{}
                if ($currentIncludeTargets.id -ne 'all_users')
                {
                    $myIncludeTargetsDisplayName = Get-M365DSCGroupDisplayNameById -GroupId $currentIncludeTargets.id
                    if ($null -eq $myIncludeTargetsDisplayName)
                    {
                        continue
                    }
                    $myIncludeTargets.Add('Id', $myIncludeTargetsDisplayName)
                }
                else
                {
                    $myIncludeTargets.Add('Id', $currentIncludeTargets.id)
                }

                if ($null -ne $currentIncludeTargets.targetType)
                {
                    $myIncludeTargets.Add('TargetType', $currentIncludeTargets.targetType.ToString())
                }

                if ($myIncludeTargets.values.Where({ $null -ne $_ }).Count -gt 0)
                {
                    $complexIncludeTargets += $myIncludeTargets
                }
            }

            #region resource generator code
            $enumState = $null
            if ($null -ne $getValue.State)
            {
                $enumState = $getValue.State.ToString()
            }
            #endregion

            $results = @{
                #region resource generator code
                FeatureSettings       = $complexFeatureSettings
                IsSoftwareOathEnabled = $getValue.isSoftwareOathEnabled
                ExcludeTargets        = $complexExcludeTargets
                IncludeTargets        = $complexIncludeTargets
                State                 = $enumState
                Id                    = $getValue.Id
                Ensure                = 'Present'
                Credential            = $this.Credential
                ApplicationId         = $this.ApplicationId
                TenantId              = $this.TenantId
                ApplicationSecret     = $this.ApplicationSecret
                CertificateThumbprint = $this.CertificateThumbprint
                CertificatePath       = $this.CertificatePath
                CertificatePassword   = $this.CertificatePassword
                ManagedIdentity       = $this.ManagedIdentity.IsPresent
                AccessTokens          = $this.AccessTokens
                #endregion
            }

            return $this.AsResult($results)
        }
        catch
        {
            $this.LogError($_, 'Error retrieving data:')

            throw
        }
    }

    [void] Set()
    {
        if ($this.RequiresPowerShellCore())
        {
            $null = $this.InvokeInPowerShellCore('Set')
            return
        }

        Write-Verbose -Message "Setting the Azure AD Authentication Method Policy Authenticator with Id {$($this.Id)}"

        Confirm-M365DSCDependencies

        $this.AddTelemetry('Set')

        $currentInstance = $this.Get().ToHashtable()
        $boundParameters = Remove-M365DSCAuthenticationParameter -BoundParameters $this.GetBoundParameters()

        if ($this.Ensure -eq 'Present')
        {
            Write-Verbose -Message "Updating the Azure AD Authentication Method Policy Authenticator with Id {$($currentInstance.Id)}"

            $updateParameters = Rename-M365DSCCimInstanceParameter -Properties $boundParameters
            $updateParameters.Remove('Id') | Out-Null

            # replace group Displayname with group id
            Update-M365DSCAuthenticationTargets -Targets $updateParameters.featureSettings.companionAppAllowedState.includeTarget
            Update-M365DSCAuthenticationTargets -Targets $updateParameters.featureSettings.companionAppAllowedState.excludeTarget
            Update-M365DSCAuthenticationTargets -Targets $updateParameters.featureSettings.displayAppInformationRequiredState.includeTarget
            Update-M365DSCAuthenticationTargets -Targets $updateParameters.featureSettings.displayAppInformationRequiredState.excludeTarget
            Update-M365DSCAuthenticationTargets -Targets $updateParameters.featureSettings.displayLocationInformationRequiredState.includeTarget
            Update-M365DSCAuthenticationTargets -Targets $updateParameters.featureSettings.displayLocationInformationRequiredState.excludeTarget
            Update-M365DSCAuthenticationTargets -Targets $updateParameters.ExcludeTargets
            Update-M365DSCAuthenticationTargets -Targets $updateParameters.IncludeTargets

            #region resource generator code
            Write-Verbose -Message "Parameters:`r`n$(ConvertTo-Json $updateParameters -Depth 10)"
            $updateParameters.Add('@odata.type', '#microsoft.graph.microsoftAuthenticatorAuthenticationMethodConfiguration')
            Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration `
                -AuthenticationMethodConfigurationId $currentInstance.Id `
                -BodyParameter $updateParameters
            #endregion
        }
        elseif ($this.Ensure -eq 'Absent' -and $currentInstance.Ensure -eq 'Present')
        {
            Write-Verbose -Message "Removing the Azure AD Authentication Method Policy Authenticator with Id {$($currentInstance.Id)}"
            #region resource generator code
            Remove-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration -AuthenticationMethodConfigurationId $currentInstance.Id
            #endregion
        }
    }

    [bool] Test()
    {
        return ([M365DSCResourceBase] $this).Test()
    }

    [string] Export()
    {
        if ($this.RequiresPowerShellCore())
        {
            return [string] $this.InvokeInPowerShellCore('Export')
        }

        $ConnectionMode = $this.Connect('MicrosoftGraph')

        Confirm-M365DSCDependencies

        $this.AddTelemetry('Export')

        try
        {
            #region resource generator code
            [array]$getValue = Get-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration `
                -AuthenticationMethodConfigurationId MicrosoftAuthenticator `
                -ErrorAction Stop | Where-Object -FilterScript { $null -ne $_.Id }
            #endregion

            $i = 1
            $dscContent = [System.Text.StringBuilder]::new()
            if ($getValue.Length -eq 0)
            {
                Write-M365DSCHost -Message $Global:M365DSCEmojiGreenCheckMark -CommitWrite
            }
            else
            {
                Write-M365DSCHost -Message "`r`n" -DeferWrite
            }
            foreach ($config in $getValue)
            {
                if ($null -ne $Global:M365DSCExportResourceInstancesCount)
                {
                    $Global:M365DSCExportResourceInstancesCount++
                }

                $displayedKey = $config.Id
                if (-not [String]::IsNullOrEmpty($config.displayName))
                {
                    $displayedKey = $config.displayName
                }
                Write-M365DSCHost -Message "    |---[$i/$($getValue.Count)] $displayedKey" -DeferWrite
                $params = @{
                    Id                    = $config.Id
                    Ensure                = 'Present'
                    Credential            = $this.Credential
                    ApplicationId         = $this.ApplicationId
                    TenantId              = $this.TenantId
                    ApplicationSecret     = $this.ApplicationSecret
                    CertificateThumbprint = $this.CertificateThumbprint
                    CertificatePath       = $this.CertificatePath
                    CertificatePassword   = $this.CertificatePassword
                    ManagedIdentity       = $this.ManagedIdentity.IsPresent
                    AccessTokens          = $this.AccessTokens
                }

                $this.ExportedInstance = $config
                $Results = $this.GetForExport($Params)
                if ($null -ne $Results.FeatureSettings)
                {
                    $complexMapping = @(
                        @{
                            Name            = 'FeatureSettings'
                            CimInstanceName = 'MicrosoftGraphMicrosoftAuthenticatorFeatureSettings'
                            IsRequired      = $False
                        }
                        @{
                            Name            = 'CompanionAppAllowedState'
                            CimInstanceName = 'MicrosoftGraphAuthenticationMethodFeatureConfiguration'
                            IsRequired      = $False
                        }
                        @{
                            Name            = 'ExcludeTarget'
                            CimInstanceName = 'AADAuthenticationMethodPolicyAuthenticatorFeatureTarget'
                            IsRequired      = $False
                        }
                        @{
                            Name            = 'IncludeTarget'
                            CimInstanceName = 'AADAuthenticationMethodPolicyAuthenticatorFeatureTarget'
                            IsRequired      = $False
                        }
                        @{
                            Name            = 'DisplayAppInformationRequiredState'
                            CimInstanceName = 'MicrosoftGraphAuthenticationMethodFeatureConfiguration'
                            IsRequired      = $False
                        }
                        @{
                            Name            = 'DisplayLocationInformationRequiredState'
                            CimInstanceName = 'MicrosoftGraphAuthenticationMethodFeatureConfiguration'
                            IsRequired      = $False
                        }
                    )
                    $complexTypeStringResult = Get-M365DSCDRGComplexTypeToString `
                        -ComplexObject $Results.FeatureSettings `
                        -CIMInstanceName 'MicrosoftGraphmicrosoftAuthenticatorFeatureSettings' `
                        -ComplexTypeMapping $complexMapping

                    if (-not [String]::IsNullOrWhiteSpace($complexTypeStringResult))
                    {
                        $Results.FeatureSettings = $complexTypeStringResult
                    }
                    else
                    {
                        $Results.Remove('FeatureSettings') | Out-Null
                    }
                }
                if ($null -ne $Results.ExcludeTargets)
                {
                    $complexTypeStringResult = Get-M365DSCDRGComplexTypeToString `
                        -ComplexObject $Results.ExcludeTargets `
                        -CIMInstanceName 'AADAuthenticationMethodPolicyAuthenticatorExcludeTarget'
                    if (-not [String]::IsNullOrWhiteSpace($complexTypeStringResult))
                    {
                        $Results.ExcludeTargets = $complexTypeStringResult
                    }
                    else
                    {
                        $Results.Remove('ExcludeTargets') | Out-Null
                    }
                }
                if ($null -ne $Results.IncludeTargets)
                {
                    $complexTypeStringResult = Get-M365DSCDRGComplexTypeToString `
                        -ComplexObject $Results.IncludeTargets `
                        -CIMInstanceName 'AADAuthenticationMethodPolicyAuthenticatorIncludeTarget'
                    if (-not [String]::IsNullOrWhiteSpace($complexTypeStringResult))
                    {
                        $Results.IncludeTargets = $complexTypeStringResult
                    }
                    else
                    {
                        $Results.Remove('IncludeTargets') | Out-Null
                    }
                }

                $currentDSCBlock = Get-M365DSCExportContentForResource -ResourceName $this.GetResourceName() `
                    -ConnectionMode $ConnectionMode `
                    -ModulePath $this.GetModulePath() `
                    -Results $Results `
                    -Credential $this.Credential `
                    -NoEscape @('FeatureSettings', 'ExcludeTargets', 'IncludeTargets')

                [void]$dscContent.Append($currentDSCBlock)
                Save-M365DSCPartialExport -Content $currentDSCBlock `
                    -FileName $Global:PartialExportFileName
                $i++
                Write-M365DSCHost -Message $Global:M365DSCEmojiGreenCheckMark -CommitWrite
            }
            return $dscContent.ToString()
        }
        catch
        {
            $this.LogError($_, 'Error during Export:')

            throw
        }
    }

    hidden [AADAuthenticationMethodPolicyAuthenticator] AsResult([System.Object] $Values)
    {
        if ($Values -is [AADAuthenticationMethodPolicyAuthenticator])
        {
            return $Values
        }

        $result = [AADAuthenticationMethodPolicyAuthenticator]::new()
        $result.ClearNonSchemaProperties()
        if ($Values -is [System.Collections.Hashtable])
        {
            $result.FromHashtable($Values)
        }

        return $result
    }
}

class MSFT_MicrosoftGraphMicrosoftAuthenticatorFeatureSettings
{
    [DscProperty()]
    [System.ComponentModel.Description('Determines whether users will be able to approve push notifications on other Microsoft applications such as Outlook Mobile.')]
    [MSFT_MicrosoftGraphAuthenticationMethodFeatureConfiguration] $CompanionAppAllowedState

    [DscProperty()]
    [System.ComponentModel.Description('Determines whether the user''s Authenticator app will show them the client app they are signing into.')]
    [MSFT_MicrosoftGraphAuthenticationMethodFeatureConfiguration] $DisplayAppInformationRequiredState

    [DscProperty()]
    [System.ComponentModel.Description('Determines whether the user''s Authenticator app will show them the geographic location of where the authentication request originated from.')]
    [MSFT_MicrosoftGraphAuthenticationMethodFeatureConfiguration] $DisplayLocationInformationRequiredState
}

class MSFT_AADAuthenticationMethodPolicyAuthenticatorExcludeTarget
{
    [DscProperty(Key)]
    [System.ComponentModel.Description('The object identifier of an Azure AD group.')]
    [System.String] $Id

    [DscProperty(Key)]
    [System.ComponentModel.Description('The type of the authentication method target. Possible values are: group and unknownFutureValue.')]
    [ValidateSet('group', 'unknownFutureValue')]
    [System.String] $TargetType
}

class MSFT_AADAuthenticationMethodPolicyAuthenticatorIncludeTarget
{
    [DscProperty(Key)]
    [System.ComponentModel.Description('The object identifier of an Azure AD group.')]
    [System.String] $Id

    [DscProperty(Key)]
    [System.ComponentModel.Description('The type of the authentication method target. Possible values are: group and unknownFutureValue.')]
    [ValidateSet('group', 'unknownFutureValue')]
    [System.String] $TargetType
}

class MSFT_MicrosoftGraphAuthenticationMethodFeatureConfiguration
{
    [DscProperty()]
    [System.ComponentModel.Description('A single entity that''s excluded from using this feature.')]
    [MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget] $ExcludeTarget

    [DscProperty()]
    [System.ComponentModel.Description('A single entity that''s allowed to use this feature.')]
    [MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget] $IncludeTarget

    [DscProperty()]
    [System.ComponentModel.Description('Enable or disable the feature. Possible values are: default, enabled, disabled, unknownFutureValue. The default value is used when the configuration hasn''t been explicitly set and uses the default behavior of Azure AD for the setting. The default value is disabled.')]
    [ValidateSet('default', 'enabled', 'disabled', 'unknownFutureValue')]
    [System.String] $State
}

class MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget
{
    [DscProperty()]
    [System.ComponentModel.Description('The ID of the entity that''s targeted in the include or exclude rule or all_users to target all users.')]
    [System.String] $Id

    [DscProperty()]
    [System.ComponentModel.Description('The kind of entity that''s targeted. The possible values are: group, administrativeUnit, role, unknownFutureValue.')]
    [ValidateSet('group', 'administrativeUnit', 'role', 'unknownFutureValue')]
    [System.String] $TargetType
}
