using module ..\_Base\M365DSCResourceBase.psm1

[DscResource()]
class IntuneCloudProvisioningPolicyWindows365 : M365DSCResourceBase
{
    [DscProperty()]
    [System.ComponentModel.Description('Indicates the Windows Autopatch settings for Cloud PCs using this provisioning policy. The settings take effect when the tenant enrolls in Autopatch and the managedType of the microsoftManagedDesktop property is set as starterManaged.')]
    [MSFT_MicrosoftGraphcloudPcProvisioningPolicyAutopatch] $Autopatch

    [DscProperty()]
    [System.ComponentModel.Description('The specific settings for Windows Autopilot that enable Windows 365 customers to experience it on Cloud PC. Supports $select.')]
    [MSFT_MicrosoftGraphcloudPcAutopilotConfiguration] $AutopilotConfiguration

    [DscProperty()]
    [System.ComponentModel.Description('The template used to name Cloud PCs provisioned using this policy. The template can contain custom text and replacement tokens, including %USERNAME:x% and %RAND:x%, which represent the user''s name and a randomly generated number, respectively. For example, CPC-%USERNAME:4%-%RAND:5% means that the name of the Cloud PC starts with CPC-, followed by a four-character username, a - character, and then five random characters. The total length of the text generated by the template can''t exceed 15 characters.')]
    [System.String] $CloudPcNamingTemplate

    [DscProperty()]
    [System.ComponentModel.Description('The provisioning policy description.')]
    [System.String] $Description

    [DscProperty(Key)]
    [System.ComponentModel.Description('The display name for the provisioning policy.')]
    [System.String] $DisplayName

    [DscProperty()]
    [System.ComponentModel.Description('Specifies a list ordered by priority on how Cloud PCs join Microsoft Entra ID (Azure AD). Supports $select.')]
    [MSFT_MicrosoftGraphcloudPcDomainJoinConfiguration[]] $DomainJoinConfigurations

    [DscProperty()]
    [System.ComponentModel.Description('True if single sign-on can access the provisioned Cloud PC. False indicates that the provisioned Cloud PC doesn''t support this feature. The default value is false. Windows 365 users can use single sign-on to authenticate to Microsoft Entra ID with passwordless options (for example, FIDO keys) to access their Cloud PC. Optional.')]
    [System.Nullable[System.Boolean]] $EnableSingleSignOn

    [DscProperty()]
    [System.ComponentModel.Description('The display name of the operating system image that is used for provisioning. For example, Windows 11 Preview + Microsoft 365 Apps 23H2 23H2.')]
    [System.String] $ImageDisplayName

    [DscProperty()]
    [System.ComponentModel.Description('The unique identifier that represents an operating system image that is used for provisioning new Cloud PCs. The format for a gallery type image is: {publisherNameofferNameskuName}. Supported values for each of the parameters are:publisher: Microsoftwindowsdesktop offer: windows-ent-cpc sku: 21h1-ent-cpc-m365, 21h1-ent-cpc-os, 20h2-ent-cpc-m365, 20h2-ent-cpc-os, 20h1-ent-cpc-m365, 20h1-ent-cpc-os, 19h2-ent-cpc-m365, and 19h2-ent-cpc-os')]
    [System.String] $ImageId

    [DscProperty()]
    [System.ComponentModel.Description('The type of operating system image (custom or gallery) that is used for provisioning on Cloud PCs. Possible values are: gallery, custom. The default value is gallery.')]
    [ValidateSet('gallery', 'custom')]
    [System.String] $ImageType

    [DscProperty()]
    [System.ComponentModel.Description('When true, the local admin is enabled for Cloud PCs false indicates that the local admin isn''t enabled for Cloud PCs. The default value is false.')]
    [System.Nullable[System.Boolean]] $LocalAdminEnabled

    [DscProperty()]
    [System.ComponentModel.Description('Specifies the type of licenses to be used when provisioning Cloud PCs using this policy. The possible values are dedicated, shared, sharedByUser, sharedByEntraGroup. The shared member is deprecated and will stop returning on April 30, 2027 going forward, use the sharedByUser member. For example, a dedicated service plan can be assigned to only one user and provision only one Cloud PC. The shared and sharedByUser plans require customers to purchase a shared service plan. Each shared license purchased can enable up to three Cloud PCs, with only one user signed in at a time. The sharedByEntraGroup plan also requires the purchase of a shared service plan. Each shared license under this plan can enable one Cloud PC, which is shared for the group according to the assignments of this policy. By default, the license type is dedicated if the provisioningType isn''t specified when you create the cloudPcProvisioningPolicy. You can''t change this property after the cloudPcProvisioningPolicy is created.')]
    [ValidateSet('dedicated', 'shared', 'sharedByUser', 'sharedByEntraGroup', 'reserve')]
    [System.String] $ProvisioningType

    [DscProperty()]
    [System.ComponentModel.Description('The Role Scope Tag Ids')]
    [System.String[]] $ScopeIds

    [DscProperty()]
    [System.ComponentModel.Description('Specifies the type of cloud object the end user can access. Possible values are: cloudPc, cloudApp. cloudPc indicates that the end user can access the entire desktop. cloudApp indicates that the end user can only access apps published under this provisioning policy. The type can''t be changed once the provisioning policy is created. If not specified during creation, the default value is cloudPc. When cloudApp is selected, the provisioningType must be sharedByEntraGroup. Cannot be changed after creation.')]
    [ValidateSet('cloudPc', 'cloudApp')]
    [System.String] $UserExperienceType

    [DscProperty()]
    [System.ComponentModel.Description('Indicates a specific Windows setting to configure during the creation of Cloud PCs for this provisioning policy. Supports $select.')]
    [MSFT_MicrosoftGraphcloudPcWindowsSetting] $WindowsSetting

    [DscProperty()]
    [System.ComponentModel.Description('Specific Windows settings to configure during the creation of Cloud PCs for this provisioning policy. Supports $select. The windowsSettings property is deprecated and will stop returning data on January 31, 2024. Going forward, use the windowsSetting property.')]
    [MSFT_MicrosoftGraphcloudPcWindowsSettings] $WindowsSettings

    [DscProperty()]
    [System.ComponentModel.Description('The unique identifier for an entity. Read-only.')]
    [System.String] $Id

    [DscProperty()]
    [System.ComponentModel.Description('Represents the assignment to the Intune policy.')]
    [MSFT_DeviceManagementConfigurationPolicyAssignments[]] $Assignments

    [DscProperty()]
    [System.ComponentModel.Description('Present ensures the policy exists, absent ensures it is removed.')]
    [ValidateSet('Present', 'Absent')]
    [System.String] $Ensure

    [DscProperty()]
    [System.ComponentModel.Description('Credentials of the Admin')]
    [System.Management.Automation.PSCredential] $Credential

    [DscProperty()]
    [System.ComponentModel.Description('Id of the Azure Active Directory application to authenticate with.')]
    [System.String] $ApplicationId

    [DscProperty()]
    [System.ComponentModel.Description('Id of the Azure Active Directory tenant used for authentication.')]
    [System.String] $TenantId

    [DscProperty()]
    [System.ComponentModel.Description('Secret of the Azure Active Directory tenant used for authentication.')]
    [System.Management.Automation.PSCredential] $ApplicationSecret

    [DscProperty()]
    [System.ComponentModel.Description('Thumbprint of the Azure Active Directory application''s authentication certificate to use for authentication.')]
    [System.String] $CertificateThumbprint

    [DscProperty()]
    [System.ComponentModel.Description('Username can be made up to anything but password will be used for CertificatePassword')]
    [System.Management.Automation.PSCredential] $CertificatePassword

    [DscProperty()]
    [System.ComponentModel.Description('Path to certificate used in service principal usually a PFX file.')]
    [System.String] $CertificatePath

    [DscProperty()]
    [System.ComponentModel.Description('Managed ID being used for authentication.')]
    [System.Nullable[System.Boolean]] $ManagedIdentity

    [DscProperty()]
    [System.ComponentModel.Description('Access token used for authentication.')]
    [System.String[]] $AccessTokens

    # Export-only. Not part of the resource schema.
    [System.String] $Filter

    [IntuneCloudProvisioningPolicyWindows365] Get()
    {
        if ($this.RequiresPowerShellCore())
        {
            $remote = [IntuneCloudProvisioningPolicyWindows365]::new()
            $remote.FromHashtable($this.InvokeInPowerShellCore('Get'))
            return $remote
        }

        Write-Verbose -Message "Getting configuration for the Intune Cloud Provisioning Policy for Windows365 with Id {$($this.Id)} and DisplayName {$($this.DisplayName)}"

        try
        {
            if (-not $this.ExportedInstance -or $this.ExportedInstance.DisplayName -ne $this.DisplayName)
            {
                $null = $this.Connect('MicrosoftGraph')

                Confirm-M365DSCDependencies

                $this.AddTelemetry('Get')

                $nullResult = $this.GetBoundParameters()
                $nullResult.Ensure = 'Absent'

                $getValue = $null

                #region resource generator code
                if (-not [System.String]::IsNullOrEmpty($this.Id))
                {
                    $getValue = Get-MgBetaDeviceManagementVirtualEndpointProvisioningPolicy `
                        -CloudPcProvisioningPolicyId $this.Id `
                        -ExpandProperty 'Assignments' `
                        -ErrorAction SilentlyContinue
                }

                if ($null -eq $getValue)
                {
                    Write-Verbose -Message "Could not find an Intune Cloud Provisioning Policy for Windows365 with Id {$($this.Id)}"

                    if (-not [System.String]::IsNullOrEmpty($this.DisplayName))
                    {
                        $getValue = Get-MgBetaDeviceManagementVirtualEndpointProvisioningPolicy `
                            -Filter "DisplayName eq '$($this.DisplayName -replace "'", "''")'" `
                            -ExpandProperty 'Assignments' `
                            -ErrorAction SilentlyContinue
                    }
                }
                #endregion
                if ($null -eq $getValue)
                {
                    Write-Verbose -Message "Could not find an Intune Cloud Provisioning Policy for Windows365 with DisplayName {$($this.DisplayName)}."
                    return $this.AsResult($nullResult)
                }
            }
            else
            {
                $getValue = $this.ExportedInstance
            }
            $resolvedId = $getValue.Id
            Write-Verbose -Message "An Intune Cloud Provisioning Policy for Windows365 with Id {$($resolvedId)} and DisplayName {$($this.DisplayName)} was found"

            #region resource generator code
            $complexAutopatch = @{}
            $complexAutopatch.Add('AutopatchGroupId', $getValue.Autopatch.autopatchGroupId)
            # TODO: Add support for AutopatchGroupDisplayName when this information is available in Microsoft Graph
            # $autopatchGroupDisplayName = <#<DisplayName>#>
            # $complexAutopatch.Add('AutopatchGroupDisplayName', $autopatchGroupDisplayName)
            if ($complexAutopatch.Values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexAutopatch = $null
            }

            $complexAutopilotConfiguration = @{}
            $complexAutopilotConfiguration.Add('ApplicationTimeoutInMinutes', $getValue.AutopilotConfiguration.applicationTimeoutInMinutes)
            $complexAutopilotConfiguration.Add('DevicePreparationProfileId', $getValue.AutopilotConfiguration.devicePreparationProfileId)
            $complexAutopilotConfiguration.Add('OnFailureDeviceAccessDenied', $getValue.AutopilotConfiguration.onFailureDeviceAccessDenied)
            if ($complexAutopilotConfiguration.Values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexAutopilotConfiguration = $null
            }

            $complexDomainJoinConfigurations = @()
            foreach ($currentDomainJoinConfigurations in $getValue.domainJoinConfigurations)
            {
                $myDomainJoinConfigurations = @{}
                if ($null -ne $currentDomainJoinConfigurations.domainJoinType)
                {
                    $myDomainJoinConfigurations.Add('DomainJoinType', $currentDomainJoinConfigurations.domainJoinType.ToString())
                }
                $myDomainJoinConfigurations.Add('OnPremisesConnectionId', $currentDomainJoinConfigurations.onPremisesConnectionId)
                if ($null -ne $currentDomainJoinConfigurations.regionGroup)
                {
                    $myDomainJoinConfigurations.Add('RegionGroup', $currentDomainJoinConfigurations.regionGroup.ToString())
                }
                $myDomainJoinConfigurations.Add('RegionName', $currentDomainJoinConfigurations.regionName)
                if ($null -ne $currentDomainJoinConfigurations.type)
                {
                    $myDomainJoinConfigurations.Add('Type', $currentDomainJoinConfigurations.type.ToString())
                }
                if ($null -ne $currentDomainJoinConfigurations.geographicLocationType)
                {
                    $myDomainJoinConfigurations.Add('GeographicLocationType', $currentDomainJoinConfigurations.geographicLocationType)
                }
                if ($myDomainJoinConfigurations.values.Where({ $null -ne $_ }).Count -gt 0)
                {
                    $complexDomainJoinConfigurations += $myDomainJoinConfigurations
                }
            }

            $complexWindowsSetting = @{}
            $complexWindowsSetting.Add('Locale', $getValue.WindowsSetting.locale)
            if ($complexWindowsSetting.Values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexWindowsSetting = $null
            }

            $complexWindowsSettings = @{}
            $complexWindowsSettings.Add('Language', $getValue.WindowsSettings.language)
            if ($complexWindowsSettings.Values.Where({ $null -ne $_ }).Count -eq 0)
            {
                $complexWindowsSettings = $null
            }
            #endregion

            #region resource generator code
            $enumImageType = $null
            if ($null -ne $getValue.ImageType)
            {
                $enumImageType = $getValue.ImageType.ToString()
            }

            $enumProvisioningType = $null
            if ($null -ne $getValue.ProvisioningType)
            {
                $enumProvisioningType = $getValue.ProvisioningType.ToString()
            }

            $enumUserExperienceType = $null
            if ($null -ne $getValue.UserExperienceType)
            {
                $enumUserExperienceType = $getValue.UserExperienceType.ToString()
            }
            #endregion

            $results = @{
                #region resource generator code
                Autopatch                = $complexAutopatch
                AutopilotConfiguration   = $complexAutopilotConfiguration
                CloudPcNamingTemplate    = $getValue.CloudPcNamingTemplate
                Description              = $getValue.Description
                DisplayName              = $getValue.DisplayName
                DomainJoinConfigurations = $complexDomainJoinConfigurations
                EnableSingleSignOn       = $getValue.EnableSingleSignOn
                ImageDisplayName         = $getValue.ImageDisplayName
                ImageId                  = $getValue.ImageId
                ImageType                = $enumImageType
                LocalAdminEnabled        = $getValue.LocalAdminEnabled
                ProvisioningType         = $enumProvisioningType
                ScopeIds                 = $getValue.ScopeIds
                UserExperienceType       = $enumUserExperienceType
                WindowsSetting           = $complexWindowsSetting
                WindowsSettings          = $complexWindowsSettings
                Id                       = $getValue.Id
                Ensure                   = 'Present'
                Credential               = $this.Credential
                ApplicationId            = $this.ApplicationId
                TenantId                 = $this.TenantId
                ApplicationSecret        = $this.ApplicationSecret
                CertificateThumbprint    = $this.CertificateThumbprint
                CertificatePath          = $this.CertificatePath
                CertificatePassword      = $this.CertificatePassword
                ManagedIdentity          = $this.ManagedIdentity.IsPresent
                #endregion
            }
            $assignmentsValues = $getValue.Assignments
            $assignmentResult = @()
            if ($assignmentsValues.Count -gt 0)
            {
                $assignmentResult += ConvertFrom-IntunePolicyAssignment -Assignments $assignmentsValues -IncludeDeviceFilter $true
            }
            $results.Add('Assignments', $assignmentResult)

            return $this.AsResult([System.Collections.Hashtable] $results)
        }
        catch
        {
            $this.LogError($_, 'Error retrieving data:')

            throw
        }
    }

    [void] Set()
    {
        if ($this.RequiresPowerShellCore())
        {
            $null = $this.InvokeInPowerShellCore('Set')
            return
        }

        Write-Verbose -Message "Setting configuration of the Intune Cloud Provisioning Policy for Windows365 with Id {$($this.Id)} and DisplayName {$($this.DisplayName)}"

        if (-not $this.GetBoundParameters().ContainsKey('Credential') -and -not [System.String]::IsNullOrEmpty($this.Autopatch.AutopatchGroupId))
        {
            throw 'Credential authentication is required when deploying with Autopatch configuration'
        }

        Confirm-M365DSCDependencies

        $this.AddTelemetry('Set')

        $currentInstance = $this.Get().ToHashtable()
        $boundParameters = Remove-M365DSCAuthenticationParameter -BoundParameters $this.GetBoundParameters()
        $managedDesktopType = 'notManaged'
        if ($boundParameters.ContainsKey('Autopatch') -and -not [System.String]::IsNullOrEmpty($boundParameters.Autopatch.AutopatchGroupId))
        {
            $managedDesktopType = 'starterManaged'
        }
        $boundParameters.Add('MicrosoftManagedDesktop', @{
            managedType = $managedDesktopType
            type        = $managedDesktopType
        })

        if ($this.Ensure -eq 'Present' -and $currentInstance.Ensure -eq 'Absent')
        {
            Write-Verbose -Message "Creating an Intune Cloud Provisioning Policy for Windows365 with DisplayName {$($this.DisplayName)}"
            $boundParameters.Remove('Assignments') | Out-Null

            $createParameters = ([Hashtable]$boundParameters).Clone()
            $createParameters = Rename-M365DSCCimInstanceParameter -Properties $createParameters
            $createParameters.Remove('Id') | Out-Null

            #region resource generator code
            $policy = New-MgBetaDeviceManagementVirtualEndpointProvisioningPolicy -BodyParameter $createParameters

            if ($policy.Id)
            {
                $assignmentsHash = ConvertTo-IntunePolicyAssignment -IncludeDeviceFilter:$true -Assignments $this.Assignments
                Update-DeviceConfigurationPolicyAssignment `
                    -DeviceConfigurationPolicyId $policy.Id `
                    -Targets $assignmentsHash `
                    -Repository 'deviceManagement/virtualEndpoint/provisioningPolicies'
            }
            #endregion
        }
        elseif ($this.Ensure -eq 'Present' -and $currentInstance.Ensure -eq 'Present')
        {
            Write-Verbose -Message "Updating the Intune Cloud Provisioning Policy for Windows365 with Id {$($currentInstance.Id)}"
            $boundParameters.Remove('Assignments') | Out-Null
            $boundParameters.Remove('ProvisioningType') | Out-Null
            $boundParameters.Add('managedBy', 'Windows365')

            $updateParameters = ([Hashtable]$boundParameters).Clone()
            $updateParameters = Rename-M365DSCCimInstanceParameter -Properties $updateParameters
            $updateParameters.Remove('Id') | Out-Null

            #region resource generator code
            Update-MgBetaDeviceManagementVirtualEndpointProvisioningPolicy `
                -CloudPcProvisioningPolicyId $currentInstance.Id `
                -BodyParameter $UpdateParameters

            $assignmentsHash = ConvertTo-IntunePolicyAssignment -IncludeDeviceFilter:$true -Assignments $this.Assignments
            Update-DeviceConfigurationPolicyAssignment `
                -DeviceConfigurationPolicyId $currentInstance.Id `
                -Targets $assignmentsHash `
                -Repository 'deviceManagement/virtualEndpoint/provisioningPolicies'
            #endregion
        }
        elseif ($this.Ensure -eq 'Absent' -and $currentInstance.Ensure -eq 'Present')
        {
            Write-Verbose -Message "Removing the Intune Cloud Provisioning Policy for Windows365 with Id {$($currentInstance.Id)}"
            #region resource generator code
            # Remove all assignments before deleting the policy
            Update-DeviceConfigurationPolicyAssignment `
                -DeviceConfigurationPolicyId $currentInstance.Id `
                -Targets @() `
                -Repository 'deviceManagement/virtualEndpoint/provisioningPolicies'
            Remove-MgBetaDeviceManagementVirtualEndpointProvisioningPolicy -CloudPcProvisioningPolicyId $currentInstance.Id
            #endregion
        }
    }

    [bool] Test()
    {
        return ([M365DSCResourceBase] $this).Test()
    }

    [string] Export()
    {
        if ($this.RequiresPowerShellCore())
        {
            return [string] $this.InvokeInPowerShellCore('Export')
        }

        $ConnectionMode = $this.Connect('MicrosoftGraph')

        Confirm-M365DSCDependencies

        $this.AddTelemetry('Export')

        try
        {
            #region resource generator code
            [array]$getValue = Get-MgBetaDeviceManagementVirtualEndpointProvisioningPolicy `
                -Filter $this.Filter `
                -ExpandProperty 'assignments' `
                -All `
                -Top 0 `
                -ErrorAction Stop
            #endregion

            $i = 1
            $dscContent = [System.Text.StringBuilder]::new()
            if ($getValue.Length -eq 0)
            {
                Write-M365DSCHost -Message $Global:M365DSCEmojiGreenCheckMark -CommitWrite
            }
            else
            {
                Write-M365DSCHost -Message "`r`n" -DeferWrite
            }
            foreach ($config in $getValue)
            {
                $displayedKey = $config.Id
                if (-not [String]::IsNullOrEmpty($config.displayName))
                {
                    $displayedKey = $config.displayName
                }
                elseif (-not [string]::IsNullOrEmpty($config.name))
                {
                    $displayedKey = $config.name
                }
                Write-M365DSCHost -Message "    |---[$i/$($getValue.Count)] $displayedKey" -DeferWrite
                $params = @{
                    Id                    = $config.Id
                    DisplayName           = $config.DisplayName
                    Ensure                = 'Present'
                    Credential            = $this.Credential
                    ApplicationId         = $this.ApplicationId
                    TenantId              = $this.TenantId
                    ApplicationSecret     = $this.ApplicationSecret
                    CertificateThumbprint = $this.CertificateThumbprint
                    CertificatePath       = $this.CertificatePath
                    CertificatePassword   = $this.CertificatePassword
                    ManagedIdentity       = $this.ManagedIdentity.IsPresent
                    AccessTokens          = $this.AccessTokens
                }

                $this.ExportedInstance = $config
                $Results = $this.GetForExport($Params)
                $rawResults = $Results.Clone()

                if ($null -ne $Results.Autopatch)
                {
                    $complexTypeStringResult = Get-M365DSCDRGComplexTypeToString `
                        -ComplexObject $Results.Autopatch `
                        -CIMInstanceName 'MicrosoftGraphCloudPcProvisioningPolicyAutopatch'
                    if (-not [String]::IsNullOrWhiteSpace($complexTypeStringResult))
                    {
                        $Results.Autopatch = $complexTypeStringResult
                    }
                    else
                    {
                        $Results.Remove('Autopatch') | Out-Null
                    }
                }
                if ($null -ne $Results.AutopilotConfiguration)
                {
                    $complexTypeStringResult = Get-M365DSCDRGComplexTypeToString `
                        -ComplexObject $Results.AutopilotConfiguration `
                        -CIMInstanceName 'MicrosoftGraphCloudPcAutopilotConfiguration'
                    if (-not [String]::IsNullOrWhiteSpace($complexTypeStringResult))
                    {
                        $Results.AutopilotConfiguration = $complexTypeStringResult
                    }
                    else
                    {
                        $Results.Remove('AutopilotConfiguration') | Out-Null
                    }
                }
                if ($null -ne $Results.DomainJoinConfigurations)
                {
                    $complexTypeStringResult = Get-M365DSCDRGComplexTypeToString `
                        -ComplexObject $Results.DomainJoinConfigurations `
                        -CIMInstanceName 'MicrosoftGraphCloudPcDomainJoinConfiguration'
                    if (-not [String]::IsNullOrWhiteSpace($complexTypeStringResult))
                    {
                        $Results.DomainJoinConfigurations = $complexTypeStringResult
                    }
                    else
                    {
                        $Results.Remove('DomainJoinConfigurations') | Out-Null
                    }
                }
                if ($null -ne $Results.MicrosoftManagedDesktop)
                {
                    $complexTypeStringResult = Get-M365DSCDRGComplexTypeToString `
                        -ComplexObject $Results.MicrosoftManagedDesktop `
                        -CIMInstanceName 'MicrosoftGraphMicrosoftManagedDesktop'
                    if (-not [String]::IsNullOrWhiteSpace($complexTypeStringResult))
                    {
                        $Results.MicrosoftManagedDesktop = $complexTypeStringResult
                    }
                    else
                    {
                        $Results.Remove('MicrosoftManagedDesktop') | Out-Null
                    }
                }
                if ($null -ne $Results.WindowsSetting)
                {
                    $complexTypeStringResult = Get-M365DSCDRGComplexTypeToString `
                        -ComplexObject $Results.WindowsSetting `
                        -CIMInstanceName 'MicrosoftGraphCloudPcWindowsSetting'
                    if (-not [String]::IsNullOrWhiteSpace($complexTypeStringResult))
                    {
                        $Results.WindowsSetting = $complexTypeStringResult
                    }
                    else
                    {
                        $Results.Remove('WindowsSetting') | Out-Null
                    }
                }
                if ($null -ne $Results.WindowsSettings)
                {
                    $complexTypeStringResult = Get-M365DSCDRGComplexTypeToString `
                        -ComplexObject $Results.WindowsSettings `
                        -CIMInstanceName 'MicrosoftGraphCloudPcWindowsSettings'
                    if (-not [String]::IsNullOrWhiteSpace($complexTypeStringResult))
                    {
                        $Results.WindowsSettings = $complexTypeStringResult
                    }
                    else
                    {
                        $Results.Remove('WindowsSettings') | Out-Null
                    }
                }

                if ($Results.Assignments)
                {
                    $complexTypeStringResult = Get-M365DSCDRGComplexTypeToString -ComplexObject $Results.Assignments -CIMInstanceName DeviceManagementConfigurationPolicyAssignments
                    if ($complexTypeStringResult)
                    {
                        $Results.Assignments = $complexTypeStringResult
                    }
                    else
                    {
                        $Results.Remove('Assignments') | Out-Null
                    }
                }

                $currentDSCBlock = Get-M365DSCExportContentForResource -ResourceName $this.GetResourceName() `
                    -ConnectionMode $ConnectionMode `
                    -ModulePath $this.GetModulePath() `
                    -Results $Results `
                    -Credential $this.Credential `
                    -NoEscape @('Assignments', 'Autopatch', 'AutopilotConfiguration', 'DomainJoinConfigurations', 'MicrosoftManagedDesktop', 'WindowsSetting', 'WindowsSettings') `
                    -RawResults $rawResults

                [void]$dscContent.Append($currentDSCBlock)
                Save-M365DSCPartialExport -Content $currentDSCBlock `
                    -FileName $Global:PartialExportFileName
                $i++
                Write-M365DSCHost -Message $Global:M365DSCEmojiGreenCheckMark -CommitWrite
            }
            return $dscContent.ToString()
        }
        catch
        {
            $this.LogError($_, 'Error during Export:')

            throw
        }
    }

    [System.Collections.Hashtable] GetCompareParameters()
    {
        return @{
            ExcludedProperties = @('GeographicLocationType', 'ProvisioningType', 'UserExperienceType')
        }
    }

    hidden [IntuneCloudProvisioningPolicyWindows365] AsResult([System.Object] $Values)
    {
        if ($Values -is [IntuneCloudProvisioningPolicyWindows365])
        {
            return $Values
        }

        $result = [IntuneCloudProvisioningPolicyWindows365]::new()
        $result.ClearNonSchemaProperties()
        if ($Values -is [System.Collections.Hashtable])
        {
            $result.FromHashtable($Values)
        }

        return $result
    }
}

class MSFT_MicrosoftGraphcloudPcProvisioningPolicyAutopatch
{
    [DscProperty()]
    [System.ComponentModel.Description('The unique identifier (ID) of a Windows Autopatch group. An Autopatch group is a logical container or unit that groups several Microsoft Entra groups and software update policies. Devices with the same Autopatch group ID share unified software update management. The default value is null that indicates that no Autopatch group is associated with the provisioning policy.')]
    [System.String] $AutopatchGroupId

    [DscProperty()]
    [System.ComponentModel.Description('The unique display name of a Windows Autopatch group.')]
    [System.String] $AutopatchGroupDisplayName
}

class MSFT_MicrosoftGraphcloudPcAutopilotConfiguration
{
    [DscProperty()]
    [System.ComponentModel.Description('Indicates the number of minutes allowed for the Autopilot application to apply the device preparation profile (DPP) configurations to the device. If the Autopilot application doesn''t finish within the specified time (applicationTimeoutInMinutes), the application error is added to the statusDetail property of the cloudPC object. The supported value is an integer between 10 and 360. Required.')]
    [System.Nullable[System.UInt32]] $ApplicationTimeoutInMinutes

    [DscProperty()]
    [System.ComponentModel.Description('The unique identifier (ID) of the Autopilot device preparation profile (DPP) that links a Windows Autopilot device preparation policy to ensure that devices are ready for users after provisioning. Required.')]
    [System.String] $DevicePreparationProfileId

    [DscProperty()]
    [System.ComponentModel.Description('Indicates whether the access to the device is allowed when the application of Autopilot device preparation profile (DPP) configurations fails or times out. If true, the status of the device is failed and the device is unable to access otherwise, the status of the device is provisionedWithWarnings and the device is allowed to access. The default value is false. Required.')]
    [System.Nullable[System.Boolean]] $OnFailureDeviceAccessDenied
}

class MSFT_MicrosoftGraphcloudPcDomainJoinConfiguration
{
    [DscProperty()]
    [System.ComponentModel.Description('Specifies the method by which the provisioned Cloud PC joins Microsoft Entra ID. If you choose the hybridAzureADJoin type, only provide a value for the onPremisesConnectionId property and leave the regionName property empty. If you choose the azureADJoin type, provide a value for either the onPremisesConnectionId or the regionName property. Possible values are: azureADJoin, hybridAzureADJoin.')]
    [ValidateSet('azureADJoin', 'hybridAzureADJoin')]
    [System.String] $DomainJoinType

    [DscProperty()]
    [System.ComponentModel.Description('The geographic location where the region is located. Read-only.')]
    [ValidateSet('default', 'asia', 'australasia', "australiaNewZealand", 'canada', 'europe', 'india', 'africa', 'usCentral', 'usEast', 'usWest', 'southAmerica', 'middleEast', 'centralAmerica', 'usGovernment', 'mexico')]
    [System.String] $GeographicLocationType

    [DscProperty()]
    [System.ComponentModel.Description('The Azure network connection ID that matches the virtual network IT admins want the provisioning policy to use when they create Cloud PCs. You can use this property in both domain join types: Azure AD joined or Hybrid Microsoft Entra joined. If you enter an onPremisesConnectionId, leave the regionName property empty.')]
    [System.String] $OnPremisesConnectionId

    [DscProperty()]
    [System.ComponentModel.Description('The logical geographic group this region belongs to. Multiple regions can belong to one region group. A customer can select a regionGroup when they provision a Cloud PC, and the Cloud PC is put in one of the regions in the group based on resource status. For example, the Europe region group contains the Northern Europe and Western Europe regions.')]
    [ValidateSet('asia', 'australasia', 'australia', 'austria', 'automatic', 'belgium', 'brazil', 'canada', 'default', 'denmark', 'euap', 'europe', 'europeUnion', 'france', 'germany', 'hongKong', 'india', 'indonesia', 'ireland', 'israel', 'italy', 'japan', 'kenya', 'malaysia', 'mexico', 'middleEast', 'netherlands', 'newZealand', 'norway', 'poland', 'singapore', 'southAmerica', 'southKorea', 'spain', 'sweden', 'switzerland', 'taiwan', 'unitedKingdom', 'unknownFutureValue', 'usCentral', 'usEast', 'usGovernment', 'usGovernmentDOD', 'usWest')]
    [System.String] $RegionGroup

    [DscProperty()]
    [System.ComponentModel.Description('The supported Azure region where the IT admin wants the provisioning policy to create Cloud PCs. The underlying virtual network is created and managed by the Windows 365 service. This can only be entered if the IT admin chooses Microsoft Entra joined as the domain join type. If you enter a regionName, leave the onPremisesConnectionId property empty. For an automatic selection, choose ''Automatic''.')]
    [System.String] $RegionName

    [DscProperty()]
    [System.ComponentModel.Description('Specifies the method by which the provisioned Cloud PC joins Microsoft Entra ID. If you choose the hybridAzureADJoin type, only provide a value for the onPremisesConnectionId property and leave regionName as empty. If you choose the azureADJoin type, provide a value for either onPremisesConnectionId or regionName. The possible values are: azureADJoin, hybridAzureADJoin. The type property is deprecated and will stop returning data on January 31, 2024. Going forward, use the domainJoinType property.')]
    [ValidateSet('azureADJoin', 'hybridAzureADJoin')]
    [System.String] $Type
}

class MSFT_MicrosoftGraphcloudPcWindowsSetting
{
    [DscProperty()]
    [System.ComponentModel.Description('The Windows language or region tag to use for language pack configuration and localization of the Cloud PC. The default value is en-US, which corresponds to English (United States).')]
    [System.String] $Locale
}

class MSFT_MicrosoftGraphcloudPcWindowsSettings
{
    [DscProperty()]
    [System.ComponentModel.Description('The Windows language/region tag to use for language pack configuration and localization of the Cloud PC. The default value is en-US, which corresponds to English (United States).')]
    [System.String] $Language
}

class MSFT_DeviceManagementConfigurationPolicyAssignments
{
    [DscProperty(Mandatory)]
    [System.ComponentModel.Description('The type of the target assignment.')]
    [ValidateSet('#microsoft.graph.cloudPcManagementGroupAssignmentTarget', '#microsoft.graph.groupAssignmentTarget', '#microsoft.graph.allLicensedUsersAssignmentTarget', '#microsoft.graph.allDevicesAssignmentTarget', '#microsoft.graph.exclusionGroupAssignmentTarget', '#microsoft.graph.configurationManagerCollectionAssignmentTarget')]
    [System.String] $dataType

    [DscProperty()]
    [System.ComponentModel.Description('The type of filter of the target assignment i.e. Exclude or Include. Possible values are:none, include, exclude.')]
    [ValidateSet('none', 'include', 'exclude')]
    [System.String] $deviceAndAppManagementAssignmentFilterType

    [DscProperty()]
    [System.ComponentModel.Description('The Id of the filter for the target assignment.')]
    [System.String] $deviceAndAppManagementAssignmentFilterId

    [DscProperty()]
    [System.ComponentModel.Description('The display name of the filter for the target assignment.')]
    [System.String] $deviceAndAppManagementAssignmentFilterDisplayName

    [DscProperty()]
    [System.ComponentModel.Description('The group Id that is the target of the assignment.')]
    [System.String] $groupId

    [DscProperty()]
    [System.ComponentModel.Description('The group Display Name that is the target of the assignment.')]
    [System.String] $groupDisplayName

    [DscProperty()]
    [System.ComponentModel.Description('The collection Id that is the target of the assignment.(ConfigMgr)')]
    [System.String] $collectionId
}
