using module ..\_Base\M365DSCResourceBase.psm1

[DscResource()]
class EXOTransportConfig : M365DSCResourceBase
{
    [DscProperty(Key)]
    [System.ComponentModel.Description('Specifies the resource is a single instance, the value must be ''Yes''.')]
    [ValidateSet('Yes')]
    [System.String] $IsSingleInstance

    [DscProperty()]
    [System.ComponentModel.Description('The AddressBookPolicyRoutingEnabled parameter controls how recipients are resolved in an organization that uses address book policies to create separate virtual organizations within the same Exchange organization.')]
    [System.Nullable[System.Boolean]] $AddressBookPolicyRoutingEnabled

    [DscProperty()]
    [System.ComponentModel.Description('Allow legacy TLS clients')]
    [System.Nullable[System.Boolean]] $AllowLegacyTLSClients

    [DscProperty()]
    [System.ComponentModel.Description('The ClearCategories parameter keeps or removes Microsoft Outlook message categories during content conversion.')]
    [System.Nullable[System.Boolean]] $ClearCategories

    [DscProperty()]
    [System.ComponentModel.Description('The ConvertDisclaimerWrapperToEml parameter specifies whether the original message will be added as a TNEF attachment or a regular EML attachment to a disclaimer.')]
    [System.Nullable[System.Boolean]] $ConvertDisclaimerWrapperToEml

    [DscProperty()]
    [System.ComponentModel.Description('The DSNConversionMode parameter controls how Exchange handles delivery status notifications that are generated by earlier versions of Exchange or other messaging systems.')]
    [System.String] $DSNConversionMode

    [DscProperty()]
    [System.ComponentModel.Description('The ExternalDelayDsnEnabled parameter specifies whether a delay delivery status notification (DSN) message should be created for external messages that couldn''t be immediately delivered. ')]
    [System.Nullable[System.Boolean]] $ExternalDelayDsnEnabled

    [DscProperty()]
    [System.ComponentModel.Description('The ExternalDsnDefaultLanguage parameter specifies which Exchange server language should be used by default when you create external DSN messages.')]
    [System.String] $ExternalDsnDefaultLanguage

    [DscProperty()]
    [System.ComponentModel.Description('The ExternalDsnLanguageDetectionEnabled parameter specifies whether the server should try to send an external DSN message in the same language as the original message that generated the notification.')]
    [System.Nullable[System.Boolean]] $ExternalDsnLanguageDetectionEnabled

    [DscProperty()]
    [System.ComponentModel.Description('The ExternalDsnReportingAuthority parameter specifies the domain in the machine-readable part of external DSN messages. ')]
    [System.String] $ExternalDsnReportingAuthority

    [DscProperty()]
    [System.ComponentModel.Description('The ExternalDsnSendHtml parameter specifies whether external DSN messages should be HTML or plain text.')]
    [System.Nullable[System.Boolean]] $ExternalDsnSendHtml

    [DscProperty()]
    [System.ComponentModel.Description('The ExternalPostmasterAddress parameter specifies the email address in the From header field of an external DSN message.')]
    [System.String] $ExternalPostmasterAddress

    [DscProperty()]
    [System.ComponentModel.Description('The HeaderPromotionModeSetting parameter specifies whether named properties are created for custom X-headers on messages received.')]
    [System.String] $HeaderPromotionModeSetting

    [DscProperty()]
    [System.ComponentModel.Description('The InternalDelayDsnEnabled parameter specifies whether a delay DSN message should be created for messages sent to or from recipients or senders in the same Exchange organization that couldn''t be immediately delivered.')]
    [System.Nullable[System.Boolean]] $InternalDelayDsnEnabled

    [DscProperty()]
    [System.ComponentModel.Description('The InternalDsnDefaultLanguage parameter specifies which Exchange server language should be used by default when you create internal DSN messages.')]
    [System.String] $InternalDsnDefaultLanguage

    [DscProperty()]
    [System.ComponentModel.Description('The InternalDsnLanguageDetectionEnabled parameter specifies whether the server should try to send an internal DSN message in the same language as the original message that generated the notification.')]
    [System.Nullable[System.Boolean]] $InternalDsnLanguageDetectionEnabled

    [DscProperty()]
    [System.ComponentModel.Description('The InternalDsnReportingAuthority parameter specifies the domain in the machine-readable part of internal DSN messages.')]
    [System.String] $InternalDsnReportingAuthority

    [DscProperty()]
    [System.ComponentModel.Description('The InternalDsnSendHtml parameter specifies whether internal DSN messages should be HTML or plain text.')]
    [System.Nullable[System.Boolean]] $InternalDsnSendHtml

    [DscProperty()]
    [System.ComponentModel.Description('The JournalMessageExpirationDays parameter extends the number of days that undeliverable journal reports are queued before they expire.')]
    [System.Nullable[System.Int32]] $JournalMessageExpirationDays

    [DscProperty()]
    [System.ComponentModel.Description('The JournalingReportNdrTo parameter specifies the email address to which journal reports are sent if the journaling mailbox is unavailable. Once set, it cannot be reset to blank again.')]
    [System.String] $JournalingReportNdrTo

    [DscProperty()]
    [System.ComponentModel.Description('The MaxRecipientEnvelopeLimit parameter specifies the maximum number of recipients in a message.')]
    [System.String] $MaxRecipientEnvelopeLimit

    [DscProperty()]
    [System.ComponentModel.Description('Reply all storm block duration hours.')]
    [System.Nullable[System.Int32]] $ReplyAllStormBlockDurationHours

    [DscProperty()]
    [System.ComponentModel.Description('Reply all storm detection minimum recipients.')]
    [System.Nullable[System.Int32]] $ReplyAllStormDetectionMinimumRecipients

    [DscProperty()]
    [System.ComponentModel.Description('Reply all storm detection minimum replies.')]
    [System.Nullable[System.Int32]] $ReplyAllStormDetectionMinimumReplies

    [DscProperty()]
    [System.ComponentModel.Description('Reply all storm protection enabled.')]
    [System.Nullable[System.Boolean]] $ReplyAllStormProtectionEnabled

    [DscProperty()]
    [System.ComponentModel.Description('The Rfc2231EncodingEnabled parameter specifies whether the RFC 2231 encoding of MIME parameters for outbound messages is enabled in your organization.')]
    [System.Nullable[System.Boolean]] $Rfc2231EncodingEnabled

    [DscProperty()]
    [System.ComponentModel.Description('The SmtpClientAuthenticationDisabled parameter specifies whether to disable authenticated SMTP (SMTP AUTH) for the whole organization.')]
    [System.Nullable[System.Boolean]] $SmtpClientAuthenticationDisabled

    [DscProperty()]
    [System.ComponentModel.Description('Credentials of the Exchange Global Admin')]
    [System.Management.Automation.PSCredential] $Credential

    [DscProperty()]
    [System.ComponentModel.Description('Id of the Azure Active Directory application to authenticate with.')]
    [System.String] $ApplicationId

    [DscProperty()]
    [System.ComponentModel.Description('Id of the Azure Active Directory tenant used for authentication.')]
    [System.String] $TenantId

    [DscProperty()]
    [System.ComponentModel.Description('Thumbprint of the Azure Active Directory application''s authentication certificate to use for authentication.')]
    [System.String] $CertificateThumbprint

    [DscProperty()]
    [System.ComponentModel.Description('Username can be made up to anything but password will be used for CertificatePassword')]
    [System.Management.Automation.PSCredential] $CertificatePassword

    [DscProperty()]
    [System.ComponentModel.Description('Path to certificate used in service principal usually a PFX file.')]
    [System.String] $CertificatePath

    [DscProperty()]
    [System.ComponentModel.Description('Managed ID being used for authentication.')]
    [System.Nullable[System.Boolean]] $ManagedIdentity

    [DscProperty()]
    [System.ComponentModel.Description('Access token used for authentication.')]
    [System.String[]] $AccessTokens

    [EXOTransportConfig] Get()
    {
        if ($this.RequiresPowerShellCore())
        {
            $remote = [EXOTransportConfig]::new()
            $remote.FromHashtable($this.InvokeInPowerShellCore('Get'))
            return $remote
        }

        Write-Verbose -Message 'Getting EXOTransportConfig'

        try
        {
            if (-not $this.ExportedInstance)
            {
                $null = $this.Connect('ExchangeOnline')

                Confirm-M365DSCDependencies

                $this.AddTelemetry('Get')

                $TransportConfigSettings = Get-TransportConfig -ErrorAction Stop
            }
            else
            {
                $TransportConfigSettings = $this.ExportedInstance
            }

            $results = @{
                IsSingleInstance                        = 'Yes'
                AddressBookPolicyRoutingEnabled         = $TransportConfigSettings.AddressBookPolicyRoutingEnabled
                AllowLegacyTLSClients                   = $TransportConfigSettings.AllowLegacyTLSClients
                ClearCategories                         = $TransportConfigSettings.ClearCategories
                ConvertDisclaimerWrapperToEml           = $TransportConfigSettings.ConvertDisclaimerWrapperToEml
                DSNConversionMode                       = $TransportConfigSettings.DSNConversionMode
                ExternalDelayDsnEnabled                 = $TransportConfigSettings.ExternalDelayDsnEnabled
                ExternalDsnDefaultLanguage              = $TransportConfigSettings.ExternalDsnDefaultLanguage.Name
                ExternalDsnLanguageDetectionEnabled     = $TransportConfigSettings.ExternalDsnLanguageDetectionEnabled
                ExternalDsnReportingAuthority           = $TransportConfigSettings.ExternalDsnReportingAuthority
                ExternalDsnSendHtml                     = $TransportConfigSettings.ExternalDsnSendHtml
                ExternalPostmasterAddress               = $TransportConfigSettings.ExternalPostmasterAddress
                HeaderPromotionModeSetting              = $TransportConfigSettings.HeaderPromotionModeSetting
                InternalDelayDsnEnabled                 = $TransportConfigSettings.InternalDelayDsnEnabled
                InternalDsnDefaultLanguage              = $TransportConfigSettings.InternalDsnDefaultLanguage
                InternalDsnLanguageDetectionEnabled     = $TransportConfigSettings.InternalDsnLanguageDetectionEnabled
                InternalDsnReportingAuthority           = $TransportConfigSettings.InternalDsnReportingAuthority
                InternalDsnSendHtml                     = $TransportConfigSettings.InternalDsnSendHtml
                JournalMessageExpirationDays            = $TransportConfigSettings.JournalMessageExpirationDays
                JournalingReportNdrTo                   = $TransportConfigSettings.JournalingReportNdrTo
                MaxRecipientEnvelopeLimit               = $TransportConfigSettings.MaxRecipientEnvelopeLimit
                ReplyAllStormBlockDurationHours         = $TransportConfigSettings.ReplyAllStormBlockDurationHours
                ReplyAllStormDetectionMinimumRecipients = $TransportConfigSettings.ReplyAllStormDetectionMinimumRecipients
                ReplyAllStormDetectionMinimumReplies    = $TransportConfigSettings.ReplyAllStormDetectionMinimumReplies
                ReplyAllStormProtectionEnabled          = $TransportConfigSettings.ReplyAllStormProtectionEnabled
                Rfc2231EncodingEnabled                  = $TransportConfigSettings.Rfc2231EncodingEnabled
                SmtpClientAuthenticationDisabled        = $TransportConfigSettings.SmtpClientAuthenticationDisabled
                Credential                              = $this.Credential
                ApplicationId                           = $this.ApplicationId
                CertificateThumbprint                   = $this.CertificateThumbprint
                CertificatePath                         = $this.CertificatePath
                CertificatePassword                     = $this.CertificatePassword
                ManagedIdentity                         = $this.ManagedIdentity.IsPresent
                TenantId                                = $this.TenantId
                AccessTokens                            = $this.AccessTokens
            }

            return $this.AsResult($results)
        }
        catch
        {
            $this.LogError($_, 'Error retrieving data:')

            throw
        }
    }

    [void] Set()
    {
        if ($this.RequiresPowerShellCore())
        {
            $null = $this.InvokeInPowerShellCore('Set')
            return
        }

        Write-Verbose -Message 'Setting EXOTransportConfig'

        Confirm-M365DSCDependencies

        $this.AddTelemetry('Set')

        $null = $this.Connect('ExchangeOnline')

        Write-Verbose -Message "Setting EXOTransportConfig with values: $(Convert-M365DscHashtableToString -Hashtable $this.GetBoundParameters())"
        $SetValues = Remove-M365DSCAuthenticationParameter -BoundParameters $this.GetBoundParameters()
        $SetValues.Remove('IsSingleInstance') | Out-Null

        if ($SetValues.JournalingReportNdrTo -eq '<>' -or [System.String]::IsNullOrEmpty($SetValues.JournalingReportNdrTo))
        {
            $SetValues.Remove('JournalingReportNdrTo') | Out-Null
        }

        Set-TransportConfig @SetValues
    }

    [bool] Test()
    {
        return ([M365DSCResourceBase] $this).Test()
    }

    [string] Export()
    {
        if ($this.RequiresPowerShellCore())
        {
            return [string] $this.InvokeInPowerShellCore('Export')
        }

        $ConnectionMode = $this.Connect('ExchangeOnline')

        Confirm-M365DSCDependencies

        $this.AddTelemetry('Export')

        try
        {
            $transportConfiguration = Get-TransportConfig -ErrorAction Stop

            $dscContent = [System.Text.StringBuilder]::new()
            if ($null -ne $Global:M365DSCExportResourceInstancesCount)
            {
                $Global:M365DSCExportResourceInstancesCount++
            }

            $Params = @{
                IsSingleInstance      = 'Yes'
                Credential            = $this.Credential
                ApplicationId         = $this.ApplicationId
                TenantId              = $this.TenantId
                CertificateThumbprint = $this.CertificateThumbprint
                CertificatePassword   = $this.CertificatePassword
                ManagedIdentity       = $this.ManagedIdentity.IsPresent
                CertificatePath       = $this.CertificatePath
                AccessTokens          = $this.AccessTokens
            }
            $this.ExportedInstance = $transportConfiguration
            $Results = $this.GetForExport($Params)
            if ($Results -is [System.Collections.Hashtable] -and $Results.Count -gt 1)
            {
                $currentDSCBlock = Get-M365DSCExportContentForResource -ResourceName $this.GetResourceName() `
                    -ConnectionMode $ConnectionMode `
                    -ModulePath $this.GetModulePath() `
                    -Results $Results `
                    -Credential $this.Credential
                [void]$dscContent.Append($currentDSCBlock)
                Save-M365DSCPartialExport -Content $currentDSCBlock `
                    -FileName $Global:PartialExportFileName

                Write-M365DSCHost -Message $Global:M365DSCEmojiGreenCheckMark -CommitWrite
            }
            else
            {
                Write-M365DSCHost -Message $Global:M365DSCEmojiRedX -CommitWrite
            }

            return $dscContent.ToString()
        }
        catch
        {
            $this.LogError($_, 'Error during Export:')

            throw
        }
    }

    hidden [EXOTransportConfig] AsResult([System.Object] $Values)
    {
        if ($Values -is [EXOTransportConfig])
        {
            return $Values
        }

        $result = [EXOTransportConfig]::new()
        $result.ClearNonSchemaProperties()
        if ($Values -is [System.Collections.Hashtable])
        {
            $result.FromHashtable($Values)
        }

        return $result
    }
}
